### ISSUE TITLE
KeyError: 'messageBreakCreate'

### ISSUE THREAD

**Issue by what7what8** [ading2210/poe-api#102]
How to reproduce: send chat break to any chatbot

---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
[<ipython-input-8-af109b9cd1ee>](https://localhost:8080/#) in <cell line: 1>()
----> 1 client.send_chat_break("chinchilla")

[/usr/local/lib/python3.10/dist-packages/poe.py](https://localhost:8080/#) in send_chat_break(self, chatbot)
    523       "chatId": self.get_bot_by_codename(chatbot)["chatId"]}
    524     )
--> 525     return result["data"]["messageBreakCreate"]["message"]
    526 
    527   def get_message_history(self, chatbot, count=25, cursor=None):

KeyError: 'messageBreakCreate'

**Comment by 7trail** [comment]
Hello,

I've confirmed that the chat break does in fact send. It's something to do with getting the data afterwards that's throwing the error- maybe they changed the JSON on the site/API end?

**Comment by ading2210** [comment]
This is already fixed in the latest commit, but I have not published a release for it yet.

**Comment by ading2210** [comment]
This has been fixed in v0.4.5.
