### ISSUE TITLE
Request to keep poe-api up simply for sage.

### ISSUE THREAD

**Issue by Tescalus** [ading2210/poe-api#103]
Hello. I am developing a cheating program for students so they can use it on their final exams via siri airpods. This is a request to keep this library up so I can still access Sage because Sage is the only bot in poe who can do a wide variety of math. The library doesn't work, and I have a final exam tomorrow. I am going to fail if it's not up. I am revolutionizing cheating with this program which uses your library, and I will give you appropriate credit.

**Comment by ading2210** [comment]
I never plan to take this repo down? Just make sure to follow the GPL and you're fine.
