### ISSUE TITLE
Tokens not working anymore

### ISSUE THREAD

**Issue by mak448a** [ading2210/poe-api#105]
I got a fresh new account and added the token in, but it says:
raise RuntimeError("Invalid token or no bots are available.")
RuntimeError: Invalid token or no bots are available.

**Comment by hidude562** [comment]
Happens to me too

**Comment by GenifeUA** [comment]
Same

**Comment by NeoPrint3D** [comment]
Let me know what they changed?

**Comment by mak448a** [comment]
It literally only started happening a few hours ago

**Comment by NeoPrint3D** [comment]
Oh dang

**Comment by ading2210** [comment]
This has been fixed in v0.4.5.

**Comment by NeoPrint3D** [comment]
Thanks so much @ading2210

**Comment by x136931283** [comment]
66666666666，老铁太快了，给你👍

**Comment by mak448a** [comment]
Thank you @ading2210 it works flawlessly

**Comment by NeoPrint3D** [comment]
Can Poe block google accounts?

**Comment by x136931283** [comment]
google ***@***.***











------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ading2210/poe-api"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年6月9日(星期五) 上午10:32
***@***.***&gt;;
抄送:&nbsp;"之卿 。   ***@***.******@***.***&gt;;
主题:&nbsp;Re: [ading2210/poe-api] Tokens not working anymore (Issue #105)





 
Can Poe block google accounts?

**Comment by NeoPrint3D** [comment]
Damn they banned 3 of my accounts

**Comment by CiaranYoung** [comment]
Oh, my God, one of my POe-apis just got busted

**Comment by hansfzlorenzana** [comment]
Same here. Even if I add a delay timer of 100 to 120 second before another request, my accounts still get banned.

**Comment by fkx816** [comment]
it occurs again

**Comment by mak448a** [comment]
Yeah it's happening again

**Comment by jiangxiaoqiang** [comment]
same issue.
