### ISSUE TITLE
Tokens not working (again) 😒

### ISSUE THREAD

**Issue by mak448a** [ading2210/poe-api#108]
# Pull request at #109
Same as #105 but it started happening again a few minutes ago

**Comment by GenifeUA** [comment]
Sane

**Comment by mak448a** [comment]
Poe must be making a lot of changes which in turn probably keeps breaking this project

**Comment by mak448a** [comment]
Found the issue: same place. line 219

**Comment by mak448a** [comment]
![image](https://github.com/ading2210/poe-api/assets/94062293/8e482bed-0844-4c69-ab38-f8c9aabdbca1)
Just comment out this line in `poe.py` and that'll be a workaround for now

**Comment by mak448a** [comment]
Change "availableBots" to "availableBotsConnection" to fix it completely

**Comment by mak448a** [comment]
I'm gonna make a pull request
