### ISSUE TITLE
what is chinchilla

### ISSUE THREAD

**Issue by thani-ath-nain** [ading2210/poe-api#11]
Does chinchilla refer to the deepmind model released last year (https://www.deepmind.com/publications/an-empirical-analysis-of-compute-optimal-large-language-model-training) or is it just some OpenAI model?

**Comment by xoiga123** [comment]
It's [Sage](https://poe.com/Sage), seems like Quora finetuned it from OpenAI? [Idk](https://www.quora.com/What-is-the-Sage-bot-on-Quora)

**Comment by ading2210** [comment]
Chinchilla is the codename for the "ChatGPT" bot inside Poe, which is just `gpt-3.5-turbo`. 
![image](https://user-images.githubusercontent.com/71154407/229605588-0166186c-0118-4645-be53-8ffb1efaf931.png)
