### ISSUE TITLE
Invalid token or no bots are available.

### ISSUE THREAD

**Issue by easykvasha** [ading2210/poe-api#112]
I registered on poe. Logged in my account. Got token from cookies, but when trying to initialise poe.Client, I get Invalid token or no bots are available. What can be the problem? But can ask questions on website (I don't use proxies)

**Comment by kebug** [comment]
the same issue at version 0.3.1, upgrade poe-api to the latest version 0.4.6, and it works.

**Comment by ading2210** [comment]
This is a duplicate of #107.
