### ISSUE TITLE
Wrong bot

### ISSUE THREAD

**Issue by Anandkrishna34** [ading2210/poe-api#116]
I made mass request using this api to a custom bot and send a message to chatgpt and the reply destination place there was gpt response.

**Comment by ading2210** [comment]
So you sent a message to ChatGPT... and got a response from the same bot?

**Comment by Anandkrishna34** [comment]
Yeah. If i tell to write a 6000 character story and send me that to my discord and i tell claude instant hi, the reply to hi will be send to my discord

**Comment by Anandkrishna34** [comment]
It might not be a big issue though ig

**Comment by ading2210** [comment]
This is a duplicate of #113.
