### ISSUE TITLE
always RuntimeError while poe.Client()

### ISSUE THREAD

**Issue by buaabarty** [ading2210/poe-api#117]
```
ERROR:websocket:error from callback <bound method Client.on_ws_connect of <poe.Client object at 0x7fd52ab6ac40>>: on_ws_connect() missing 1 required positional argument: 'ws'
ERROR:websocket:error from callback <bound method Client.on_ws_close of <poe.Client object at 0x7fd52ab6ac40>>: on_ws_close() missing 3 required positional arguments: 'ws', 'close_status_code', and 'close_message'
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.8/dist-packages/poe.py", line 123, in __init__
    self.connect_ws()
  File "/usr/local/lib/python3.8/dist-packages/poe.py", line 393, in connect_ws
    raise RuntimeError("Timed out waiting for websocket to connect.")
RuntimeError: Timed out waiting for websocket to connect.
```

I execute `poe.Client('my_cookie')` after register and login a new account. I've tried many times but always runtime error. How to resolve it?

**Comment by ading2210** [comment]
Are you using a proxy? Those can sometimes cause issues with websockets if you're not using the socks5h protcol, since many http proxy servers will chose to block websockets.

**Comment by Ezzzzz4** [comment]
> Are you using a proxy? Those can sometimes cause issues with websockets if you're not using the socks5h protcol, since many http proxy servers will chose to block websockets.

Same problem, but I am not using any proxy. When I try to run it in google colab everything is fine. Problem may be in python script lib for godot engine to run python code.

Sorry for my English, it isn't my first language :)

**Comment by ading2210** [comment]
@buaabarty @Ezzzzz4 
Can you make sure that you have the latest version of the [websocket-client](https://pypi.org/project/websocket-client/) library installed?

**Comment by Ezzzzz4** [comment]
> @buaabarty @Ezzzzz4 Can you make sure that you have the latest version of the [websocket-client](https://pypi.org/project/websocket-client/) library installed?

Thanks for reply, I checked and I am sure that I installed the latest (1.5.3)

**Comment by buaabarty** [comment]
> @buaabarty @Ezzzzz4 Can you make sure that you have the latest version of the [websocket-client](https://pypi.org/project/websocket-client/) library installed?

Thanks, I've updated the WebSocket-client library and the runtime error has disappeared.

**Comment by valokobito** [comment]
I have installed the latest version, and increate timeout from `5` to `12` and I still have the issue
