### ISSUE TITLE
Supressing websocket errors

### ISSUE THREAD

**Issue by notBradPitt** [ading2210/poe-api#121]
I have my own script to handle disconnection in another thread in the background, but I still get the websocket error and it's messing with the user input. I can't seem to find what's causing this error to be displayed, especially since everything still works fine after the message is displayed. Is there any way to suppress this error?

```
ERROR:websocket:Connection to remote host was lost. - goodbye
WARNING:root:Websocket closed with status None: None
```

**Comment by ading2210** [comment]
Simply do `import logging` then `poe.logger.setLevel(logging.CRITICAL)` which should suppress all error messages.
