### ISSUE TITLE
RuntimeError("Invalid token or no bots are available.")

### ISSUE THREAD

**Issue by zmansoft** [ading2210/poe-api#122]
help please, web service is ok, token is uptodate, but this program raises this error:
  File "F:\PycharmProjects\poe-api-main\poe-api\src\poe.py", line 88, in __init__
    self.setup_connection()
  File "F:\PycharmProjects\poe-api-main\poe-api\src\poe.py", line 95, in setup_connection
    self.bots = self.get_bots(download_next_data=False)
  File "F:\PycharmProjects\poe-api-main\poe-api\src\poe.py", line 152, in get_bots
    raise RuntimeError("Invalid token or no bots are available.")
RuntimeError: Invalid token or no bots are available.

**Comment by zmansoft** [comment]
problem solved, something changed in poe.com


  def get_bots(self, download_next_data=True):
    logger.info("Downloading all bots...")
    if download_next_data:
      next_data = self.get_next_data(overwrite_vars=True)
    else:
      next_data = self.next_data

    # if not "availableBots" in self.viewer:
    if not "availableBotsConnection" in self.viewer:
      raise RuntimeError("Invalid token or no bots are available.")
    bot_list = self.viewer["availableBotsConnection"]['edges']

    threads = []
    bots = {}

    def get_bot_thread(bot):
      chat_data = self.get_bot(bot['node']["displayName"])
      bots[chat_data["defaultBotObject"]["nickname"]] = chat_data

**Comment by Anandkrishna34** [comment]
Alr

**Comment by zmansoft** [comment]
oh no, it's because my version is not the newest...
