### ISSUE TITLE
ChatGPT (chinchilla) doesn't work with the API

### ISSUE THREAD

**Issue by Bohaska** [ading2210/poe-api#124]
A day ago, I found that all of my ChatGPT queries were returning a RuntimeError saying that I reached my Daily Limit for ChatGPT, which I believe is excessively unlikely. I think that this is probably caused by a bug in poe-api, as the daily limit error is raised whenever a message cannot be found.

**Comment by ading2210** [comment]
Your account has probably been banned. See #118.
