### ISSUE TITLE
Stopped working

### ISSUE THREAD

**Issue by Denintendator** [ading2210/poe-api#128]
Seems like they updated their api and now it shows this error:
`Traceback (most recent call last):
  File "example.py", line 9, in <module>
    client = poe.Client(token)
  File "/Users/user/Library/Python/3.8/lib/python/site-packages/poe.py", line 123, in __init__
    self.connect_ws()
  File "/Users/user/Library/Python/3.8/lib/python/site-packages/poe.py", line 366, in connect_ws
    self.setup_connection()
  File "/Users/user/Library/Python/3.8/lib/python/site-packages/poe.py", line 149, in setup_connection
    self.next_data = self.get_next_data(overwrite_vars=True)
  File "/Users/user/Library/Python/3.8/lib/python/site-packages/poe.py", line 198, in get_next_data
    self.viewer = next_data["props"]["pageProps"]["payload"]["viewer"]`

**Comment by alqasemy2020** [comment]
`payload` should be replaced w/ `data` in both
https://github.com/ading2210/poe-api/blob/47a053f2e88d9738e36115b9be3d1e0ae13fc4a4/poe-api/src/poe.py#L198
and
https://github.com/ading2210/poe-api/blob/47a053f2e88d9738e36115b9be3d1e0ae13fc4a4/poe-api/src/poe.py#L209
also in lines 262 and 267.

#129 should fix this issue

**Comment by x136931283** [comment]
good 解决了我的问题，么么哒

**Comment by akl7777777** [comment]
好像还是不行,更新了最新代码之后,一直提示这个,是不是之前的模型名称叫beaver,后来官方换成GPT-4.json了
WARNING:root:Server returned a status code of 404 while downloading https://poe.com/_next/data/mNtTbYuk87oLN4p8oS78b/beaver.json. Retrying (10/10)...
捕获到 RuntimeError: Failed to download https://poe.com/_next/data/mNtTbYuk87oLN4p8oS78b/beaver.json too many times.

**Comment by win4r** [comment]
确实不行啊，老外在度假哎，怎么修复啊？

**Comment by akl7777777** [comment]
哈哈,我来改改试试

**Comment by win4r** [comment]
兄弟盟，有兴趣一起重写个vercel版的或者用其他语言重写个。我建立个微信交流群吧：
这是我的哔哩哔哩，我有开发的多AI集成应用：[哔哩哔哩](https://space.bilibili.com/3493277319825652)
![image](https://github.com/ading2210/poe-api/assets/42172631/496d7209-79dc-49b2-ad2c-ca796666b451)

**Comment by ading2210** [comment]
This should have been fixed in v0.4.7.
