### ISSUE TITLE
Update required due to changes in index.json

### ISSUE THREAD

**Issue by fkx816** [ading2210/poe-api#134]
The web version of poe has updated the code for index.json, changing the previous "payload" to "data". Replacing ["pageProps"]["payload"] with ["pageProps"]["data"] in the poe.py file seems to make it work again.

**Comment by win4r** [comment]
兄弟盟，进二次开发群讨论：
![image](https://github.com/ading2210/poe-api/assets/42172631/07c672a6-a6a4-4edf-9bce-44a73438eaa3)

**Comment by AhmadSci** [comment]
waiting for it to be fixed :)

**Comment by ading2210** [comment]
This has already been fixed in v0.4.7. 

See #128.
