### ISSUE TITLE
timeout error

### ISSUE THREAD

**Issue by huyremy** [ading2210/poe-api#137]
socket timeout       
------------
File "/home/huyremy/.local/lib/python3.7/site-packages/poe.py", line 502, in send_message
    raise RuntimeError("Response timed out.")
RuntimeError: Response timed out.
------------
Stop and restart it run well but it will be timeout error in few minutes later.
------------
Please check and correct it. Thanks

**Comment by ichuixue** [comment]
Same problem here. A restart will fix this error, but don't know why. Maybe it has something to do with the websocket.

**Comment by huyremy** [comment]
fixed !

**Comment by huyremy** [comment]
re-error again !

**Comment by huyremy** [comment]
fixed !
