### ISSUE TITLE
Run temp_message error

### ISSUE THREAD

**Issue by LiMingchen159** [ading2210/poe-api#144]
- I know this question may be stupid, but I struggled for a long time.
- Is this library working now?
- I used version `0.4.8.`
- And this is my first time run it, then I got this error

File "C:\Users\111\AppData\Local\Programs\Python\Python38\lib\threading.py", line 932, in _bootstrap_inner
    self.run()
  File "C:\Users\111\AppData\Local\Programs\Python\Python38\lib\threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\111\AppData\Local\Programs\Python\Python38\lib\site-packages\poe.py", line 233, in get_bot_thread
    chat_data = self.get_bot(bot["node"]["displayName"])
  File "C:\Users\111\AppData\Local\Programs\Python\Python38\lib\site-packages\poe.py", line 214, in get_bot
    chat_data = data["pageProps"]["data"]["chatOfBotDisplayName"]
KeyError: 'chatOfBotDisplayName'
Exception in thread Thread-3:
Traceback (most recent call last):
  File "C:\Users\111\AppData\Local\Programs\Python\Python38\lib\threading.py", line 932, in _bootstrap_inner
    self.run()
  File "C:\Users\111\AppData\Local\Programs\Python\Python38\lib\threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\111\AppData\Local\Programs\Python\Python38\lib\site-packages\poe.py", line 233, in get_bot_thread
    chat_data = self.get_bot(bot["node"]["displayName"])
  File "C:\Users\111\AppData\Local\Programs\Python\Python38\lib\site-packages\poe.py", line 214, in get_bot
    chat_data = data["pageProps"]["data"]["chatOfBotDisplayName"]
KeyError: 'chatOfBotDisplayName'
Exception in thread Thread-5:
Traceback (most recent call last):
  File "C:\Users\111\AppData\Local\Programs\Python\Python38\lib\threading.py", line 932, in _bootstrap_inner
    self.run()
  File "C:\Users\111\AppData\Local\Programs\Python\Python38\lib\threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\111\AppData\Local\Programs\Python\Python38\lib\site-packages\poe.py", line 233, in get_bot_thread
    chat_data = self.get_bot(bot["node"]["displayName"])
  File "C:\Users\111\AppData\Local\Programs\Python\Python38\lib\site-packages\poe.py", line 214, in get_bot
    chat_data = data["pageProps"]["data"]["chatOfBotDisplayName"]
KeyError: 'chatOfBotDisplayName'
Exception in thread Thread-1:
Traceback (most recent call last):
  File "C:\Users\111\AppData\Local\Programs\Python\Python38\lib\threading.py", line 932, in _bootstrap_inner
    self.run()
  File "C:\Users\111\AppData\Local\Programs\Python\Python38\lib\threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\111\AppData\Local\Programs\Python\Python38\lib\site-packages\poe.py", line 233, in get_bot_thread
    chat_data = self.get_bot(bot["node"]["displayName"])
  File "C:\Users\111\AppData\Local\Programs\Python\Python38\lib\site-packages\poe.py", line 214, in get_bot
    chat_data = data["pageProps"]["data"]["chatOfBotDisplayName"]
KeyError: 'chatOfBotDisplayName'
Exception in thread Thread-7:
Traceback (most recent call last):
  File "C:\Users\111\AppData\Local\Programs\Python\Python38\lib\threading.py", line 932, in _bootstrap_inner
    self.run()
  File "C:\Users\111\AppData\Local\Programs\Python\Python38\lib\threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\111\AppData\Local\Programs\Python\Python38\lib\site-packages\poe.py", line 233, in get_bot_thread
    chat_data = self.get_bot(bot["node"]["displayName"])
  File "C:\Users\111\AppData\Local\Programs\Python\Python38\lib\site-packages\poe.py", line 214, in get_bot
    chat_data = data["pageProps"]["data"]["chatOfBotDisplayName"]
KeyError: 'chatOfBotDisplayName'
Exception in thread Thread-4:
Traceback (most recent call last):
  File "C:\Users\111\AppData\Local\Programs\Python\Python38\lib\threading.py", line 932, in _bootstrap_inner
    self.run()
  File "C:\Users\111\AppData\Local\Programs\Python\Python38\lib\threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\111\AppData\Local\Programs\Python\Python38\lib\site-packages\poe.py", line 233, in get_bot_thread
    chat_data = self.get_bot(bot["node"]["displayName"])
  File "C:\Users\111\AppData\Local\Programs\Python\Python38\lib\site-packages\poe.py", line 214, in get_bot
    chat_data = data["pageProps"]["data"]["chatOfBotDisplayName"]
KeyError: 'chatOfBotDisplayName'
Exception in thread Thread-2:
Traceback (most recent call last):
  File "C:\Users\111\AppData\Local\Programs\Python\Python38\lib\threading.py", line 932, in _bootstrap_inner
    self.run()
  File "C:\Users\111\AppData\Local\Programs\Python\Python38\lib\threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\111\AppData\Local\Programs\Python\Python38\lib\site-packages\poe.py", line 233, in get_bot_thread
    chat_data = self.get_bot(bot["node"]["displayName"])
  File "C:\Users\111\AppData\Local\Programs\Python\Python38\lib\site-packages\poe.py", line 214, in get_bot
    chat_data = data["pageProps"]["data"]["chatOfBotDisplayName"]
KeyError: 'chatOfBotDisplayName'
INFO:root:Subscribing to mutations
WARNING:websocket:websocket connected
INFO:root:Sending message to capybara: Who are you?
WARNING:root:Server returned a status code of 404 while downloading https://poe.com/_next/data/2WUKJiaLlyAttUI7qPryw/capybara.json. Retrying (1/10)...
WARNING:root:Server returned a status code of 404 while downloading https://poe.com/_next/data/2WUKJiaLlyAttUI7qPryw/capybara.json. Retrying (2/10)...
WARNING:root:Server returned a status code of 404 while downloading https://poe.com/_next/data/2WUKJiaLlyAttUI7qPryw/capybara.json. Retrying (3/10)...
WARNING:root:Server returned a status code of 404 while downloading https://poe.com/_next/data/2WUKJiaLlyAttUI7qPryw/capybara.json. Retrying (4/10)...
WARNING:root:Server returned a status code of 404 while downloading https://poe.com/_next/data/2WUKJiaLlyAttUI7qPryw/capybara.json. Retrying (5/10)...
WARNING:root:Server returned a status code of 404 while downloading https://poe.com/_next/data/2WUKJiaLlyAttUI7qPryw/capybara.json. Retrying (6/10)...
WARNING:root:Server returned a status code of 404 while downloading https://poe.com/_next/data/2WUKJiaLlyAttUI7qPryw/capybara.json. Retrying (7/10)...
WARNING:root:Server returned a status code of 404 while downloading https://poe.com/_next/data/2WUKJiaLlyAttUI7qPryw/capybara.json. Retrying (8/10)...
WARNING:root:Server returned a status code of 404 while downloading https://poe.com/_next/data/2WUKJiaLlyAttUI7qPryw/capybara.json. Retrying (9/10)...
WARNING:root:Server returned a status code of 404 while downloading https://poe.com/_next/data/2WUKJiaLlyAttUI7qPryw/capybara.json. Retrying (10/10)...
Traceback (most recent call last):
  File "D:\Git_project\Duolingo_auto_answer\temp.py", line 20, in <module>
    for chunk in client.send_message("capybara", message, with_chat_break=True):
  File "C:\Users\111\AppData\Local\Programs\Python\Python38\lib\site-packages\poe.py", line 484, in send_message
    chat_id = self.get_bot_by_codename(chatbot)["chatId"]
  File "C:\Users\111\AppData\Local\Programs\Python\Python38\lib\site-packages\poe.py", line 254, in get_bot_by_codename
    return self.get_bot(bot_codename)
  File "C:\Users\111\AppData\Local\Programs\Python\Python38\lib\site-packages\poe.py", line 210, in get_bot
    data = request_with_retries(self.session.get, url).json()
  File "C:\Users\111\AppData\Local\Programs\Python\Python38\lib\site-packages\poe.py", line 53, in request_with_retries
    raise RuntimeError(f"Failed to download {url} too many times.")
RuntimeError: Failed to download https://poe.com/_next/data/2WUKJiaLlyAttUI7qPryw/capybara.json too many times.

**Comment by ading2210** [comment]
I can't seem to reproduce this. Everything works fine for me:
```
$ python3 examples/temporary_message.py "MTc0UWHEqreij7vCRi9BLg%3D%3D"
INFO:root:Setting up session...
INFO:root:Downloading next_data...
INFO:root:Downloading channel data...
INFO:root:Downloading all bots...
INFO:root:Subscribing to mutations
INFO:websocket:Websocket connected
INFO:root:Sending message to capybara: Who are you?
I am Sage, a language model developed by OpenAI. I am designed to generate human-like text based on the input I receive. I can answer questions, provide explanations, write stories, and assist with a variety of tasks, among other things. How can I assist you today?INFO:root:Purging messages from capybara
INFO:root:Downloading 50 messages from capybara
INFO:root:Deleting messages: [1597102246, 1597102073, 1597102024]
```

**Comment by huyremy** [comment]
> * I know this question may be stupid, but I struggled for a long time.
> 
>     * Is this library working now?
> 
>     * I used version `0.4.8.`
> 
>     * And this is my first time run it, then I got this error
> 
> 
> File "C:\Users\111\AppData\Local\Programs\Python\Python38\lib\threading.py", line 932, in _bootstrap_inner self.run() File "C:\Users\111\AppData\Local\Programs\Python\Python38\lib\threading.py", line 870, in run self._target(*self._args, **self._kwargs) File "C:\Users\111\AppData\Local\Programs\Python\Python38\lib\site-packages\poe.py", line 233, in get_bot_thread chat_data = self.get_bot(bot["node"]["displayName"]) File "C:\Users\111\AppData\Local\Programs\Python\Python38\lib\site-packages\poe.py", line 214, in get_bot chat_data = data["pageProps"]["data"]["chatOfBotDisplayName"] KeyError: 'chatOfBotDisplayName' Exception in thread Thread-3: Traceback (most recent call last): File "C:\Users\111\AppData\Local\Programs\Python\Python38\lib\threading.py", line 932, in _bootstrap_inner self.run() File "C:\Users\111\AppData\Local\Programs\Python\Python38\lib\threading.py", line 870, in run self._target(*self._args, **self._kwargs) File "C:\Users\111\AppData\Local\Programs\Python\Python38\lib\site-packages\poe.py", line 233, in get_bot_thread chat_data = self.get_bot(bot["node"]["displayName"]) File "C:\Users\111\AppData\Local\Programs\Python\Python38\lib\site-packages\poe.py", line 214, in get_bot chat_data = data["pageProps"]["data"]["chatOfBotDisplayName"] KeyError: 'chatOfBotDisplayName' Exception in thread Thread-5: Traceback (most recent call last): File "C:\Users\111\AppData\Local\Programs\Python\Python38\lib\threading.py", line 932, in _bootstrap_inner self.run() File "C:\Users\111\AppData\Local\Programs\Python\Python38\lib\threading.py", line 870, in run self._target(*self._args, **self._kwargs) File "C:\Users\111\AppData\Local\Programs\Python\Python38\lib\site-packages\poe.py", line 233, in get_bot_thread chat_data = self.get_bot(bot["node"]["displayName"]) File "C:\Users\111\AppData\Local\Programs\Python\Python38\lib\site-packages\poe.py", line 214, in get_bot chat_data = data["pageProps"]["data"]["chatOfBotDisplayName"] KeyError: 'chatOfBotDisplayName' Exception in thread Thread-1: Traceback (most recent call last): File "C:\Users\111\AppData\Local\Programs\Python\Python38\lib\threading.py", line 932, in _bootstrap_inner self.run() File "C:\Users\111\AppData\Local\Programs\Python\Python38\lib\threading.py", line 870, in run self._target(*self._args, **self._kwargs) File "C:\Users\111\AppData\Local\Programs\Python\Python38\lib\site-packages\poe.py", line 233, in get_bot_thread chat_data = self.get_bot(bot["node"]["displayName"]) File "C:\Users\111\AppData\Local\Programs\Python\Python38\lib\site-packages\poe.py", line 214, in get_bot chat_data = data["pageProps"]["data"]["chatOfBotDisplayName"] KeyError: 'chatOfBotDisplayName' Exception in thread Thread-7: Traceback (most recent call last): File "C:\Users\111\AppData\Local\Programs\Python\Python38\lib\threading.py", line 932, in _bootstrap_inner self.run() File "C:\Users\111\AppData\Local\Programs\Python\Python38\lib\threading.py", line 870, in run self._target(*self._args, **self._kwargs) File "C:\Users\111\AppData\Local\Programs\Python\Python38\lib\site-packages\poe.py", line 233, in get_bot_thread chat_data = self.get_bot(bot["node"]["displayName"]) File "C:\Users\111\AppData\Local\Programs\Python\Python38\lib\site-packages\poe.py", line 214, in get_bot chat_data = data["pageProps"]["data"]["chatOfBotDisplayName"] KeyError: 'chatOfBotDisplayName' Exception in thread Thread-4: Traceback (most recent call last): File "C:\Users\111\AppData\Local\Programs\Python\Python38\lib\threading.py", line 932, in _bootstrap_inner self.run() File "C:\Users\111\AppData\Local\Programs\Python\Python38\lib\threading.py", line 870, in run self._target(*self._args, **self._kwargs) File "C:\Users\111\AppData\Local\Programs\Python\Python38\lib\site-packages\poe.py", line 233, in get_bot_thread chat_data = self.get_bot(bot["node"]["displayName"]) File "C:\Users\111\AppData\Local\Programs\Python\Python38\lib\site-packages\poe.py", line 214, in get_bot chat_data = data["pageProps"]["data"]["chatOfBotDisplayName"] KeyError: 'chatOfBotDisplayName' Exception in thread Thread-2: Traceback (most recent call last): File "C:\Users\111\AppData\Local\Programs\Python\Python38\lib\threading.py", line 932, in _bootstrap_inner self.run() File "C:\Users\111\AppData\Local\Programs\Python\Python38\lib\threading.py", line 870, in run self._target(*self._args, **self._kwargs) File "C:\Users\111\AppData\Local\Programs\Python\Python38\lib\site-packages\poe.py", line 233, in get_bot_thread chat_data = self.get_bot(bot["node"]["displayName"]) File "C:\Users\111\AppData\Local\Programs\Python\Python38\lib\site-packages\poe.py", line 214, in get_bot chat_data = data["pageProps"]["data"]["chatOfBotDisplayName"] KeyError: 'chatOfBotDisplayName' INFO:root:Subscribing to mutations WARNING:websocket:websocket connected INFO:root:Sending message to capybara: Who are you? WARNING:root:Server returned a status code of 404 while downloading https://poe.com/_next/data/2WUKJiaLlyAttUI7qPryw/capybara.json. Retrying (1/10)... WARNING:root:Server returned a status code of 404 while downloading https://poe.com/_next/data/2WUKJiaLlyAttUI7qPryw/capybara.json. Retrying (2/10)... WARNING:root:Server returned a status code of 404 while downloading https://poe.com/_next/data/2WUKJiaLlyAttUI7qPryw/capybara.json. Retrying (3/10)... WARNING:root:Server returned a status code of 404 while downloading https://poe.com/_next/data/2WUKJiaLlyAttUI7qPryw/capybara.json. Retrying (4/10)... WARNING:root:Server returned a status code of 404 while downloading https://poe.com/_next/data/2WUKJiaLlyAttUI7qPryw/capybara.json. Retrying (5/10)... WARNING:root:Server returned a status code of 404 while downloading https://poe.com/_next/data/2WUKJiaLlyAttUI7qPryw/capybara.json. Retrying (6/10)... WARNING:root:Server returned a status code of 404 while downloading https://poe.com/_next/data/2WUKJiaLlyAttUI7qPryw/capybara.json. Retrying (7/10)... WARNING:root:Server returned a status code of 404 while downloading https://poe.com/_next/data/2WUKJiaLlyAttUI7qPryw/capybara.json. Retrying (8/10)... WARNING:root:Server returned a status code of 404 while downloading https://poe.com/_next/data/2WUKJiaLlyAttUI7qPryw/capybara.json. Retrying (9/10)... WARNING:root:Server returned a status code of 404 while downloading https://poe.com/_next/data/2WUKJiaLlyAttUI7qPryw/capybara.json. Retrying (10/10)... Traceback (most recent call last): File "D:\Git_project\Duolingo_auto_answer\temp.py", line 20, in for chunk in client.send_message("capybara", message, with_chat_break=True): File "C:\Users\111\AppData\Local\Programs\Python\Python38\lib\site-packages\poe.py", line 484, in send_message chat_id = self.get_bot_by_codename(chatbot)["chatId"] File "C:\Users\111\AppData\Local\Programs\Python\Python38\lib\site-packages\poe.py", line 254, in get_bot_by_codename return self.get_bot(bot_codename) File "C:\Users\111\AppData\Local\Programs\Python\Python38\lib\site-packages\poe.py", line 210, in get_bot data = request_with_retries(self.session.get, url).json() File "C:\Users\111\AppData\Local\Programs\Python\Python38\lib\site-packages\poe.py", line 53, in request_with_retries raise RuntimeError(f"Failed to download {url} too many times.") RuntimeError: Failed to download https://poe.com/_next/data/2WUKJiaLlyAttUI7qPryw/capybara.json too many times.

Try to change: chat_data = data["pageProps"]["data"]["chatOfBotDisplayName"] ----> chat_data = r.json()["pageProps"]["data"]["chatOfBotHandle"] then run again. Goodluck !

**Comment by LiMingchen159** [comment]
I forgot to say, This solution works well, but please be careful to make the "r" a global variable or pass it into the function. Thanks, guys!
