### ISSUE TITLE
Poe 403 forbiden

### ISSUE THREAD

**Issue by XuZhengzhuo** [ading2210/poe-api#150]
It seems that my IP can access google but not poe, is there any suitable solution? 

The poe web version can be used normally.

![image](https://github.com/ading2210/poe-api/assets/38523665/23371b5f-6c22-464e-9595-769935fbb81f)

**Comment by win4r** [comment]
![image](https://github.com/ading2210/poe-api/assets/42172631/6d7df691-304c-4508-9bfe-2e02df32dde4)

**Comment by ading2210** [comment]
Do you get a 403 status when running poe-api? Your screenshot only lists the output for the curl command.

**Comment by ichuixue** [comment]
Do not use the Japanese IP

**Comment by yunlianwangluo** [comment]
> Do not use the Japanese IP

I got the same result, just using IP from LA...

**Comment by CaoYunzhou** [comment]
yes i have 403 return err

**Comment by leeeawa** [comment]
same problem

**Comment by ading2210** [comment]
Going to merge this with #158.
