### ISSUE TITLE
Bot name of Google-Palm

### ISSUE THREAD

**Issue by ndhieunguyen** [ading2210/poe-api#153]
I realize there is a new bot on poe.com, Google-Palm. I want to use it in poe-api, but I do not know its name. Can anyone provide me with its name, please?

**Comment by Anandkrishna34** [comment]
> I realize there is a new bot on poe.com, Google-Palm. I want to use it in poe-api, but I do not know its name. Can anyone provide me with its name, please?

print(json.dumps(client.bot_names, indent=2))

**Comment by ichuixue** [comment]
acouchy
