### ISSUE TITLE
Blocking Warning

### ISSUE THREAD

**Issue by A2020GK** [ading2210/poe-api#154]
Please add a warning stating that your Poe - account may be blocked if you use this API.

**Comment by kaz875** [comment]
is that true - anyone got blocked already?

**Comment by A2020GK** [comment]
I got blocked.

**Comment by A2020GK** [comment]
![image](https://github.com/ading2210/poe-api/assets/89532641/d58ad059-2f31-4149-8b85-5e82b1a4a9e8)

**Comment by hkplau** [comment]
After using this api for testing 10 messages, I got blocked as well.

**Comment by WeeAris** [comment]
I also had one account banned, and several others were restricted from creating or modifying bots.

**Comment by claell** [comment]
Can those of you who got banned or restricted add some more information on your usage?

Did you send excessive amount of requests (total or per minute)? Other details? Would be good to know how to avoid getting banned or restricted.

**Comment by WeeAris** [comment]
> 

For me, it didn't take long to get banned after exceeding 120 requests per hour.
