### ISSUE TITLE
chat work but purge error

### ISSUE THREAD

**Issue by cx9208** [ading2210/poe-api#17]
purge_conversation or get history got an error,but send message work:

import poe
client = poe.Client("","")
print(client.bot_names)
message = "hi"
for chunk in client.send_message("chinchilla", message):
   print(chunk["text_new"], end="", flush=True)
client.purge_conversation("chinchilla", count=2)

{'capybara': 'Sage', 'beaver': 'GPT-4', 'a2_2': 'Claude+', 'a2': 'Claude-instant', 'chinchilla': 'ChatGPT', 'nutria': 'Dragonfly'}
Hello again! Is there something you would like to ask or discuss?Traceback (most recent call last):
  File "e:\desktop\chatGPT\testpoe.py", line 9, in <module>
    his=client.purge_conversation("chinchilla", count=2)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\C\AppData\Local\Programs\Python\Python311\Lib\site-packages\poe.py", line 338, in purge_conversation
    last_messages = self.get_message_history(chatbot, count=50)[::-1]
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\C\AppData\Local\Programs\Python\Python311\Lib\site-packages\poe.py", line 325, in get_message_history
    return result["data"]["node"]["messagesConnection"]["edges"]
           ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^
TypeError: 'NoneType' object is not subscriptable

**Comment by ading2210** [comment]
Seems like Poe changed it so that the `cursor` variable is required. I'm working on a fix right now.

**Comment by ading2210** [comment]
This has been fixed in 0.2.7.
