### ISSUE TITLE
V0.4.11  Failed to download https://poe.com too many times.

### ISSUE THREAD

**Issue by PoetGcc** [ading2210/poe-api#179]
https://github.com/ading2210/poe-api/pull/174 is work, but when update poe-api 0.4.11，don't work

**Comment by buaabarty** [comment]
I have the same situation.

**Comment by claell** [comment]
For me, it doesn't matter. Both 0.4.10 and 0.4.11 give this error. Yesterday, less than 24 hours ago, it still worked with 0.4.10 for me.

**Comment by claell** [comment]
Seems to be a possible duplicate of #173, though.

**Comment by noseon** [comment]
https://github.com/canxin121/poe-api he changed something and it's working now I don't know why the author here didn't merge the code

**Comment by LiMingchen159** [comment]
I got the same error.

**Comment by ading2210** [comment]
Duplicate of #158.
