### ISSUE TITLE
ModuleNotFoundError: No module named 'poe'

### ISSUE THREAD

**Issue by CRCODE22** [ading2210/poe-api#18]
I installed these requirements:
pip3 install poe-client
pip3 install poe-api

Getting this error:
poe-api\examples>temporary_message.py
Traceback (most recent call last):
File "D:\poe-api\examples\temporary_message.py", line 1, in <module>
import poe
ModuleNotFoundError: No module named 'poe'

**Comment by ading2210** [comment]
I'm not sure why that's happening, since it works perfectly fine for me. Maybe (this)[https://stackoverflow.com/q/53720324] stackoverflow post could help? 

Also, the `poe-client` package is completely unrelated to this project or the Poe website. You should probably uninstall it.

**Comment by Poiz0ned** [comment]
Got the same error, @CRCODE22 did you manage to fix it?

**Comment by CRCODE22** [comment]
> Got the same error, @CRCODE22 did you manage to fix it?

I have not managed to fix it yet.

**Comment by BSG-Walter** [comment]
> > Got the same error, @CRCODE22 did you manage to fix it?
> 
> I have not managed to fix it yet.

you need to install it locally.
clone the repo, go to the poe-api folder and run this command:

pip install .

**Comment by TheLime1** [comment]
just use `python` instead of `python3`

**Comment by hongrunhui** [comment]
`cd ./poe-api` 
`sudo python3 setup.py install`

**Comment by hongrunhui** [comment]
`sudo /usr/local/opt/python@3.11/bin/python3.11 examples/send_message.py`

**Comment by hongrunhui** [comment]
python3.9都不行，艹 必须3.11
