### ISSUE TITLE
new error，Failed to download https://poe.com/api/gql_POST too many times.

### ISSUE THREAD

**Issue by PoetGcc** [ading2210/poe-api#180]
I used the latest code, the commit is  fix explore_bots ，the error log:

Failed to download https://poe.com/api/gql_POST too many times.

**Comment by yeqiu006** [comment]
me too

**Comment by yas7epan** [comment]
SAME

**Comment by naruto716** [comment]
same.

**Comment by yas7epan** [comment]
SAME

**Comment by yongli233** [comment]
OMG SAME

**Comment by Shirasawaz** [comment]
same...

WARNING:root:Server returned a status code of 400 while downloading https://poe.com/api/gql_POST. Retrying (1/10)...
WARNING:root:Server returned a status code of 400 while downloading https://poe.com/api/gql_POST. Retrying (2/10)...
WARNING:root:Server returned a status code of 400 while downloading https://poe.com/api/gql_POST. Retrying (3/10)...
WARNING:root:Server returned a status code of 400 while downloading https://poe.com/api/gql_POST. Retrying (4/10)...
WARNING:root:Server returned a status code of 400 while downloading https://poe.com/api/gql_POST. Retrying (5/10)...
WARNING:root:Server returned a status code of 400 while downloading https://poe.com/api/gql_POST. Retrying (6/10)...
WARNING:root:Server returned a status code of 400 while downloading https://poe.com/api/gql_POST. Retrying (7/10)...
WARNING:root:Server returned a status code of 400 while downloading https://poe.com/api/gql_POST. Retrying (8/10)...
WARNING:root:Server returned a status code of 400 while downloading https://poe.com/api/gql_POST. Retrying (9/10)...
WARNING:root:Server returned a status code of 400 while downloading https://poe.com/api/gql_POST. Retrying (10/10)...

**Comment by akl7777777** [comment]
same

**Comment by noseon** [comment]
RuntimeError: Failed to download https://poe.com/api/gql_POST too many times.

**Comment by figgefigge** [comment]
````
import poe
import logging
poe.logger.setLevel(logging.DEBUG)
poe.headers = {
  "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/108.0",
  "Accept": "*/*",
  "Accept-Encoding": "gzip, deflate, br",
  "Accept-Language": "sv-SE,sv;q=0.8,en-US;q=0.5,en;q=0.3",
  "Te": "trailers",
  "Upgrade-Insecure-Requests": "1"
}
poe.client_identifier = "firefox108"
token = "XXXXXXXXXXXXf7ILVKlSjg%3D%3D"
client = poe.Client(token)
````

````
INFO:root:Setting up session...
INFO:root:Downloading next_data...
INFO:root:Downloading channel data...
INFO:root:Downloading all bots...
INFO:root:Subscribing to mutations
WARNING:root:Server returned a status code of 400 while downloading https://poe.com/api/gql_POST. Retrying (1/10)...
WARNING:root:Server returned a status code of 400 while downloading https://poe.com/api/gql_POST. Retrying (2/10)...
WARNING:root:Server returned a status code of 400 while downloading https://poe.com/api/gql_POST. Retrying (3/10)...
WARNING:root:Server returned a status code of 400 while downloading https://poe.com/api/gql_POST. Retrying (4/10)...
WARNING:root:Server returned a status code of 400 while downloading https://poe.com/api/gql_POST. Retrying (5/10)...
WARNING:root:Server returned a status code of 400 while downloading https://poe.com/api/gql_POST. Retrying (6/10)...
WARNING:root:Server returned a status code of 400 while downloading https://poe.com/api/gql_POST. Retrying (7/10)...
WARNING:root:Server returned a status code of 400 while downloading https://poe.com/api/gql_POST. Retrying (8/10)...
WARNING:root:Server returned a status code of 400 while downloading https://poe.com/api/gql_POST. Retrying (9/10)...
WARNING:root:Server returned a status code of 400 while downloading https://poe.com/api/gql_POST. Retrying (10/10)...
````

**Comment by kalindir-lunar** [comment]
same, but if you follow this link from a browser, it doesn't let me in either.

**Comment by figgefigge** [comment]
When im using a browser I get good response. Cookie, __cf_bm also beeing sent, is this new? This is the request sent from browser: 
```
POST /api/gql_POST HTTP/3
Host: poe.com
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/115.0
Accept: */*
Accept-Language: sv-SE,sv;q=0.8,en-US;q=0.5,en;q=0.3
Accept-Encoding: gzip, deflate, br
Referer: https://poe.com/
poe-formkey: 76ccfb704e421ca3947e1752a9930637
poe-tchannel: poe-chan49-8888-vqhbwhdnaoqvbkvcrtix
Content-Type: application/json
poe-tag-id: bbb370b1dbd16401287ce19f28b45c69
Content-Length: 417
Origin: https://poe.com
DNT: 1
Connection: keep-alive
Cookie: p-b=XXXXXXXXxvcfa2uBzUtLNg%3D%3D; __cf_bm=c95FNUudugOJCqGaW8iqdbs5lwZSNHo5TBbSaVE43Jk-1690056047-0-ASlHxUcTlErtFvFgGJRW0WIrj3jK3HfeEnBKGGc2hdXAhP5Uj567xAmV9RwVV6PTtwgPQylzNaBJEALy2q/AKeQ=; g_state={"i_p":1690063250463,"i_l":1}
Sec-Fetch-Dest: empty
Sec-Fetch-Mode: cors
Sec-Fetch-Site: same-origin
TE: trailers
´´´

**Comment by tkbstudios** [comment]
same issue

**Comment by noseon** [comment]
It's the same as claude's api that I made a line from a post with all the code. the poe api must be dynamic at a key point as it is a ws system and it is more complicated to do this but i have to look a little deeper on monday and change something by doing fork because i use this api too much and being without it is bad =/

**Comment by LiMingchen159** [comment]
same again

**Comment by phamxtien** [comment]
Me too

**Comment by ading2210** [comment]
It looks like Poe changed the format for `gql_POST` requests, instead requiring a hash of the GQL query instead of the full query.

**Comment by ading2210** [comment]
Can someone test the latest commit to see if this is fixed? I need to know if the hash in `gql_POST` is the underlying issue.

**Comment by PoetGcc** [comment]
> Can someone test the latest commit to see if this is fixed? I need to know if the hash in `gql_POST` is the underlying issue.
> 
> ```
> pip3 install git+https://github.com/ading2210/poe-api.git
> ```

its worked. Thank you

**Comment by ading2210** [comment]
This should have been fixed in v0.4.12. Changing `gql_POST` to use hashes will come sometime in v0.5.x.

**Comment by noseon** [comment]
[/usr/local/lib/python3.10/dist-packages/poe.py](https://localhost:8080/#) in extract_formkey(self, html)
    200   def extract_formkey(self, html):
    201     script_regex = r'<script>if\(.+\)throw new Error;(.+)</script>'
--> 202     script_text = re.search(script_regex, html).group(1)
    203     key_regex = r'var .="([0-9a-f]+)",'
    204     key_text = re.search(key_regex, script_text).group(1)

AttributeError: 'NoneType' object has no attribute 'group'

**Comment by noseon** [comment]
> Extractly, I test post with hash and it run very well. ![Screenshot from 2023-07-23 11-59-35](https://user-images.githubusercontent.com/2125897/255375018-c215b780-4e27-4279-a877-6ce1e761e88e.png)

you are using postman or proxy? I'll see using this api here as a base and recreate another one from scratch more simplified when you have these changes to fix it faster or maybe the people from quora are looking at this api and changing
