### ISSUE TITLE
cannot get gql_POST, status code 400

### ISSUE THREAD

**Issue by brianler** [ading2210/poe-api#181]
This looks good to me, but I just have one question. How did you find the `WpuLMiXEKKE98j56k` string? Was it just hardcoded in the client JS somewhere? If so, wouldn't it be really easy for Quora to break this library simply by changing that string again?

_Originally posted by @ading2210 in https://github.com/ading2210/poe-api/issues/39#issuecomment-1509475143_

Testing has found that self.gql_headers["poe-formkey"] can change, sometimes it is a 32-character string: ce7201131f80b20558f1a290a4690a4c, and sometimes it is a 33-character string: ce7201131f80b20558f1a290a4690a4c0. And it seems that the algorithm for generating the "poe-tag-id" in the headers has changed, resulting in the following problem.

```
WARNING:root:Server returned a status code of 400 while downloading https://poe.com/api/gql_POST. Retrying (2/10)...
WARNING:root:Server returned a status code of 400 while downloading https://poe.com/api/gql_POST. Retrying (3/10)...
WARNING:root:Server returned a status code of 400 while downloading https://poe.com/api/gql_POST. Retrying (4/10)...
WARNING:root:Server returned a status code of 400 while downloading https://poe.com/api/gql_POST. Retrying (5/10)...
WARNING:root:Server returned a status code of 400 while downloading https://poe.com/api/gql_POST. Retrying (6/10)...
WARNING:root:Server returned a status code of 400 while downloading https://poe.com/api/gql_POST. Retrying (7/10)...
WARNING:root:Server returned a status code of 400 while downloading https://poe.com/api/gql_POST. Retrying (8/10)...
WARNING:root:Server returned a status code of 400 while downloading https://poe.com/api/gql_POST. Retrying (9/10)...
WARNING:root:Server returned a status code of 400 while downloading https://poe.com/api/gql_POST. Retrying (10/10)...
Traceback (most recent call last):
  File "C:\Users\alfred\e\Python\server\main 3.11.py", line 54, in <module>
    ai = poe.Client(token)
  File "C:\Users\alfred\AppData\Local\Programs\Python\Python311\Lib\site-packages\poe.py", line 79, in __init__
    self.subscribe()
  File "C:\Users\alfred\AppData\Local\Programs\Python\Python311\Lib\site-packages\poe.py", line 160, in subscribe
    result = self.send_query("SubscriptionsMutation", {
  File "C:\Users\alfred\AppData\Local\Programs\Python\Python311\Lib\site-packages\poe.py", line 147, in send_query
    r = request_with_retries(self.session.post, self.gql_url, json=payload, headers=self.gql_headers)
  File "C:\Users\alfred\AppData\Local\Programs\Python\Python311\Lib\site-packages\poe.py", line 37, in request_with_retries
      raise RuntimeError(f"Failed to download {url} too many times.")
RuntimeError: Failed to download https://poe.com/api/gql_POST too many times.
```

**Comment by noseon** [comment]
def extract_formkey(self, html):
     script_regex = r'<script>if\(.+\)throw new Error;(.+)</script>'
     script_text = re.search(script_regex, html).group(1)
     key_regex = r'var .="([0-9a-f]+)",'
     key_text = re.search(key_regex, script_text).group(1)
     cipher_regex = r'.\[(\d+)\]=.\[(\d+)\]'
     cipher_pairs = re.findall(cipher_regex, script_text) 

what could have happened and that id changed name or location

**Comment by ZikaiSun** [comment]
I'm new to revert engineering. Just some clue that may or may not help:

<img width="574" alt="image" src="https://github.com/ading2210/poe-api/assets/40849708/dde49af4-f615-4a8c-9737-821c0ce92867">

<img width="326" alt="image" src="https://github.com/ading2210/poe-api/assets/40849708/f67f09f2-d54b-4b1c-a81d-6d238ff7197a">

<img width="704" alt="image" src="https://github.com/ading2210/poe-api/assets/40849708/8d69c1bd-4c02-4f65-89bd-f4ea70d905be">


In line 1974, the string changed to "Jb1hi3fg1MxZpzYfy", which is used to generate the "poe-tag-id" header.

Changing this only do not make it work. Since the raised error of this program changed
However, there seems another change when request /api/setting.json

<img width="491" alt="image" src="https://github.com/ading2210/poe-api/assets/40849708/b1124e18-81df-4c56-91e7-67abea1d25d3">

I'm not sure weather this "If-None-Match:" newly change....

**Comment by xieqing520** [comment]
> I'm new to revert engineering. Just some clues that may or may not help:
> 
> <img alt="image" width="612" src="https://user-images.githubusercontent.com/40849708/255356228-6f24b91d-a85b-4e0c-a26d-da5e7dfcb0b8.png"> <img alt="image" width="326" src="https://user-images.githubusercontent.com/40849708/255356076-f67f09f2-d54b-4b1c-a81d-6d238ff7197a.png"> <img alt="image" width="704" src="https://user-images.githubusercontent.com/40849708/255356088-8d69c1bd-4c02-4f65-89bd-f4ea70d905be.png">
> On line 1974, the string is "Jb1hi3fg1MxZpzYfy", which appears to be used in generating the "poe-tag-id" header.
> 
> Changing this only do not make it work. Since the error presented by the program shifted, I guess there may be additional changes elsewhere. I suspect there might be another change occurring when requesting /api/setting.json.
> 
> <img alt="image" width="491" src="https://user-images.githubusercontent.com/40849708/255355906-b1124e18-81df-4c56-91e7-67abea1d25d3.png">
> I'm not sure weather the "If-None-Match:" has changed or not....
> 
> Looking forward to be rescued...

you are right, it work

**Comment by brianler** [comment]
Cool, the problem has been solved, here's the solution.

Modify the `...\site-packages\poe.py` file.
```python
# -----Original
script_regex = r'<script>if\(.+\)throw new Error;(.+)</script>'
script_text = re.search(script_regex, html).group(1)
# -----Modified
# script_regex = r'<script>if\(.+\)throw new Error;(.+)</script>'
# script_text = re.search(script_regex, html).group(1)
script_text = html

# -----Original
self.formkey = self.extract_formkey(r.text)
# -----Modified
self.formkey = self.extract_formkey(r.text)[:32]

# -----Original
base_string = payload + self.gql_headers["poe-formkey"][:32] + "WpuLMiXEKKE98j56k"
# -----Modified
base_string = payload + self.gql_headers["poe-formkey"][:32] + "Jb1hi3fg1MxZpzYfy"
```
