### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'group'

### ISSUE THREAD

**Issue by greengeckowizard** [ading2210/poe-api#182]
I asked GPT432K a few times and its all linking back to the poe.py here so that's why am posting this here but this is from my project in which the error occurs in I'm running windows in this log with python 3.11 version 

```
←[32mINFO←[0m:     Started server process [←[36m6728←[0m]
←[32mINFO←[0m:     Waiting for application startup.
←[31mERROR←[0m:    Traceback (most recent call last):
  File "C:\Users\YES\AppData\Local\Programs\Python\Python311\Lib\site-packages\starlette\routing.py", line 677, in lifespan
    async with self.lifespan_context(app) as maybe_state:
  File "C:\Users\YES\AppData\Local\Programs\Python\Python311\Lib\site-packages\starlette\routing.py", line 566, in __aenter__
    await self._router.startup()
  File "C:\Users\YES\AppData\Local\Programs\Python\Python311\Lib\site-packages\starlette\routing.py", line 654, in startup
    await handler()
  File "C:\Users\YES\Downloads\poe-server-main\poe-server-main\server.py", line 220, in startup_event
    poe_provider = PoeProvider(
                   ^^^^^^^^^^^^
  File "C:\Users\YES\Downloads\poe-server-main\poe-server-main\server.py", line 100, in __init__
    self.clients = [
                   ^
  File "C:\Users\YES\Downloads\poe-server-main\poe-server-main\server.py", line 101, in <listcomp>
    poe.Client(token=token, proxy=proxy)
  File "C:\Users\YES\AppData\Local\Programs\Python\Python311\Lib\site-packages\poe.py", line 155, in __init__
    self.connect_ws()
  File "C:\Users\YES\AppData\Local\Programs\Python\Python311\Lib\site-packages\poe.py", line 413, in connect_ws
    self.setup_connection()
  File "C:\Users\YES\AppData\Local\Programs\Python\Python311\Lib\site-packages\poe.py", line 181, in setup_connection
    self.next_data = self.get_next_data(overwrite_vars=True)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\YES\AppData\Local\Programs\Python\Python311\Lib\site-packages\poe.py", line 229, in get_next_data
    self.formkey = self.extract_formkey(r.text)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\YES\AppData\Local\Programs\Python\Python311\Lib\site-packages\poe.py", line 206, in extract_formkey
    script_text = re.search(script_regex, html).group(1)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'group'

←[31mERROR←[0m:    Application startup failed. Exiting.
```

**Comment by greengeckowizard** [comment]
gpt-4-32k has suggested a change this to fix the NoneType error I can send and that got rid of it but its having another issue after it.

here's the suggested fix:


The error you're encountering is due to the `re.search(script_regex, html).group(1)` line in the `extract_formkey` method not finding a match in the HTML string it's searching. 

To fix this issue, you need to make sure that the regular expression (`script_regex`) is correctly formed and matches the expected pattern in the HTML string. 

The error message indicates that the `re.search` function doesn't find a match and returns `None`, which leads to the `AttributeError` when trying to call `.group(1)` on `None`.

Here is the fix:

```python
def extract_formkey(self, html):
    script_regex = r'<script>if\(.+\)throw new Error;(.+)</script>'
    match = re.search(script_regex, html)

    if match is None: 
        raise ValueError('Cannot find script_regex in HTML')

    script_text = match.group(1)
    key_regex = r'var .="([0-9a-f]+)",'
    key_text = re.search(key_regex, script_text).group(1)
    cipher_regex = r'.\[(\d+)\]=.\[(\d+)\]'
    cipher_pairs = re.findall(cipher_regex, script_text)

    formkey_list = [""] * len(cipher_pairs)
    for pair in cipher_pairs:
      formkey_index, key_index = map(int, pair)
      formkey_list[formkey_index] = key_text[key_index]
    formkey = "".join(formkey_list)[:-1] # credit to @aditiaryan on realizing my mistake

    return formkey
```

Please note that the error might also be due to a change in the webpage's structure. If that's the case, you would need to adjust `script_regex` accordingly. This fix assumes the regular expression is correct and the HTML does contain a match. If the match is not found, it raises a `ValueError` with an appropriate message.

**Comment by greengeckowizard** [comment]
ok after that I saw this error from my program after that suggested code has been implemented (which indicated it was poe.py as the error changed)

```
C:\Users\YES\Downloads\poe-server-main\poe-server-main>uvicorn server:app --host 0.0.0.0 --port 8000
←[32mINFO←[0m:     Started server process [←[36m3676←[0m]
←[32mINFO←[0m:     Waiting for application startup.
←[31mERROR←[0m:    Traceback (most recent call last):
  File "C:\Users\YES\AppData\Local\Programs\Python\Python311\Lib\site-packages\starlette\routing.py", line 677, in lifespan
    async with self.lifespan_context(app) as maybe_state:
  File "C:\Users\YES\AppData\Local\Programs\Python\Python311\Lib\site-packages\starlette\routing.py", line 566, in __aenter__
    await self._router.startup()
  File "C:\Users\YES\AppData\Local\Programs\Python\Python311\Lib\site-packages\starlette\routing.py", line 654, in startup
    await handler()
  File "C:\Users\YES\Downloads\poe-server-main\poe-server-main\server.py", line 220, in startup_event
    poe_provider = PoeProvider(
                   ^^^^^^^^^^^^
  File "C:\Users\YES\Downloads\poe-server-main\poe-server-main\server.py", line 100, in __init__
    self.clients = [
                   ^
  File "C:\Users\YES\Downloads\poe-server-main\poe-server-main\server.py", line 101, in <listcomp>
    poe.Client(token=token, proxy=proxy)
  File "C:\Users\YES\AppData\Local\Programs\Python\Python311\Lib\site-packages\poe.py", line 155, in __init__
    self.connect_ws()
  File "C:\Users\YES\AppData\Local\Programs\Python\Python311\Lib\site-packages\poe.py", line 418, in connect_ws
    self.setup_connection()
  File "C:\Users\YES\AppData\Local\Programs\Python\Python311\Lib\site-packages\poe.py", line 181, in setup_connection
    self.next_data = self.get_next_data(overwrite_vars=True)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\YES\AppData\Local\Programs\Python\Python311\Lib\site-packages\poe.py", line 234, in get_next_data
    self.formkey = self.extract_formkey(r.text)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\YES\AppData\Local\Programs\Python\Python311\Lib\site-packages\poe.py", line 209, in extract_formkey
    raise ValueError('Cannot find script_regex in HTML')
ValueError: Cannot find script_regex in HTML

←[31mERROR←[0m:    Application startup failed. Exiting.
```

**Comment by xieqing520** [comment]
delete  the two line;
script_regex = r'<script>if\(.+\)throw new Error;(.+)</script>'
    match = re.search(script_regex, html)

**Comment by greengeckowizard** [comment]
I hope you guys can figure it out but this is how far I got and its leading to that poe changed their HTML structure this is what gpt-4-32k said about it:

It seems your issue lies in the `extract_formkey` function not being able to find a match in the HTML content it's parsing. The regular expression used `r'<script>if\(.+\)throw new Error;(.+)</script>'` might not be matching any content in your HTML. 

Let's make a change to the `extract_formkey` function to print out the HTML content when a match isn't found. This way, we can verify if the issue lies with the regex or the HTML content:

```python
def extract_formkey(self, html):
    script_regex = r'<script>if\(.+\)throw new Error;(.+)</script>'
    match = re.search(script_regex, html)

    if match is None: 
        print("HTML content:", html)  # print the HTML content
        raise ValueError('Cannot find script_regex in HTML')

    script_text = match.group(1)
    key_regex = r'var .="([0-9a-f]+)",'
    key_text = re.search(key_regex, script_text).group(1)
    cipher_regex = r'.\[(\d+)\]=.\[(\d+)\]'
    cipher_pairs = re.findall(cipher_regex, script_text)

    formkey_list = [""] * len(cipher_pairs)
    for pair in cipher_pairs:
        formkey_index, key_index = map(int, pair)
        formkey_list[formkey_index] = key_text[key_index]
    formkey = "".join(formkey_list)[:-1] # credit to @aditiaryan on realizing my mistake

    return formkey
```

After applying this change, run your application again. If the ValueError is raised, it will print out the HTML content before raising the error. You can inspect this HTML content to verify if the issue lies with the regular expression or the HTML content.

However, remember this is a diagnostic step, not a final solution. To solve the problem, you may need to adjust the regular expressions in the `extract_formkey` function to match the actual structure of the HTML page you are dealing with. 

Without knowledge of the actual HTML structure of the page, it's not possible to provide a more specific solution.

**Comment by greengeckowizard** [comment]
> delete the two line; script_regex = r'<script>if(.+)throw new Error;(.+)</script>' match = re.search(script_regex, html)

oh thanks I'll test now

**Comment by xieqing520** [comment]
and     

#script_text = match.group(1)
script_text = html

**Comment by greengeckowizard** [comment]
ok :+1:  

> and
> 
> #script_text = match.group(1) script_text = html

**Comment by xieqing520** [comment]
it can run, but you will find new error:   down xxxxx/gql_POST  too many times #180 
changed the line code:

base_string = payload + self.gql_headers["poe-formkey"] + "WpuLMiXEKKE98j56k"

as:

base_string = payload + self.gql_headers["poe-formkey"] + "Jb1hi3fg1MxZpzYfy"

it's salt is changed when yesterday night

**Comment by ading2210** [comment]
> I hope you guys can figure it out but this is how far I got and its leading to that poe changed their HTML structure this is what gpt-4-32k said about it

FYI copy-pasting errors into an LLM doesn't help at all.

**Comment by 445022889** [comment]
已经解决
extract_formkey 方法中 去掉 script_regex 和 script_text，重新加script_text = html
base_string = payload + self.gql_headers["poe-formkey"] + "Jb1hi3fg1MxZpzYfy"
即可
<img width="688" alt="image" src="https://github.com/ading2210/poe-api/assets/8262562/b10ba611-0c08-4772-b9e9-70bc44fb3dfc">
<img width="576" alt="image" src="https://github.com/ading2210/poe-api/assets/8262562/1ef80a37-562a-4976-aa36-bea8639022a5">

**Comment by ading2210** [comment]
This has been fixed in version 0.4.12.

**Comment by canxin121** [comment]
I have refactored a new asynchronous [Async-Poe-Client](https://github.com/canxin121/Async-Poe-Client) in modern ways based on httpx and websockets, and i added some new functions.

**Comment by ading2210** [comment]
> I have refactored a new asynchronous [Async-Poe-Client](https://github.com/canxin121/Async-Poe-Client) in modern ways based on httpx and websockets, and i added some new functions.It could be faster, more stable and more convenient.
FYI this is violating the GNU GPL v3 which poe-api is licensed under.
