### ISSUE TITLE
Poe has updated the algorithm for formkey again.

### ISSUE THREAD

**Issue by canxin121** [ading2210/poe-api#184]
<img width="633" alt="image" src="https://github.com/ading2210/poe-api/assets/69547456/707ec429-77dd-4659-a2b6-9e05242ca341">

**Comment by ading2210** [comment]
I'm investigating this right now.

**Comment by wong2** [comment]
I'm also investigating this for my project [ChatHub](https://github.com/chathub-dev/chathub), seems this upgrade is impossible to implement by hand, the only solution I can think of is to execute the code in a JavaScript runtime.

**Comment by ading2210** [comment]
I'm probably going to just blindly eval the obfuscated JS instead of re-implementing it in Python.

**Comment by asce0** [comment]
@ading2210  got the same error :(

**Comment by canxin121** [comment]
<img width="899" alt="image" src="https://github.com/ading2210/poe-api/assets/69547456/4d32a472-1ad2-416a-967e-761c94f1f9ac">
already got it, wait for me

**Comment by ading2210** [comment]
This has been fixed in v0.4.13.

**Comment by asce0** [comment]
note that quickjs package is not compatible with Python 3.11, so you may face an issue while trying to upgrade poe-api 0.4.13 :D

**Comment by PoetGcc** [comment]
> note that quickjs package is not compatible with Python 3.11, so you may face an issue while trying to upgrade poe-api 0.4.13 :D

same。What to do？

**Comment by asce0** [comment]
@PoetGcc I just downgraded python from 3.11 to 3.10.10 and it worked successfully
