### ISSUE TITLE
Consistent 400 Error after updating to poe-api 0.4.13

### ISSUE THREAD

**Issue by neekohuncho** [ading2210/poe-api#188]
python3 examples/temporary_message.py "XXXXXXXXXXXXXXXX"

INFO:root:Setting up session...
INFO:root:Downloading next_data...
INFO:root:Downloading channel data...
INFO:root:Downloading all bots...
INFO:root:Subscribing to mutations
WARNING:root:Server returned a status code of 400 while downloading https://poe.com/api/gql_POST. Retrying (1/10)...
WARNING:root:Server returned a status code of 400 while downloading https://poe.com/api/gql_POST. Retrying (2/10)...
WARNING:root:Server returned a status code of 400 while downloading https://poe.com/api/gql_POST. Retrying (3/10)...
WARNING:root:Server returned a status code of 400 while downloading https://poe.com/api/gql_POST. Retrying (4/10)...
WARNING:root:Server returned a status code of 400 while downloading https://poe.com/api/gql_POST. Retrying (5/10)...
WARNING:root:Server returned a status code of 400 while downloading https://poe.com/api/gql_POST. Retrying (6/10)...
WARNING:root:Server returned a status code of 400 while downloading https://poe.com/api/gql_POST. Retrying (7/10)...
WARNING:root:Server returned a status code of 400 while downloading https://poe.com/api/gql_POST. Retrying (8/10)...
WARNING:root:Server returned a status code of 400 while downloading https://poe.com/api/gql_POST. Retrying (9/10)...
WARNING:root:Server returned a status code of 400 while downloading https://poe.com/api/gql_POST. Retrying (10/10)...
Traceback (most recent call last):
  File "/Users/neeko/Downloads/poe-api-main-5/examples/temporary_message.py", line 9, in <module>
    client = poe.Client(token)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/poe.py", line 153, in __init__
    self.connect_ws()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/poe.py", line 403, in connect_ws
    self.setup_connection()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/poe.py", line 195, in setup_connection
    self.subscribe()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/poe.py", line 361, in subscribe
    result = self.send_query("SubscriptionsMutation", {
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/poe.py", line 348, in send_query
    r = request_with_retries(self.session.post, self.gql_url, data=payload, headers=headers)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/poe.py", line 83, in request_with_retries
    raise RuntimeError(f"Failed to download {url} too many times.")
RuntimeError: Failed to download https://poe.com/api/gql_POST too many times.

**Comment by ading2210** [comment]
Looks like Poe started to enforce hashes on the `gql_POST` requests.

**Comment by claell** [comment]
Wow, Poe recently seem to break a lot. Let's hope, we can get into a more usable state soon.

**Comment by ading2210** [comment]
> Looks like Poe started to enforce hashes on the `gql_POST` requests.

On second thought, I don't think this is the case. Perhaps they changed the algorithm for `poe-tag-id` again.

**Comment by GPT5free** [comment]
how to solve it？

**Comment by siriani** [comment]
I tried to check, and indeed the package broke. Something must have changed on poe.com

**Comment by xieqing520** [comment]
the formKey is error ,  because  it check the quickJs.

**Comment by xieqing520** [comment]
this line is check the quickjs,when find it  return error form key
![image](https://github.com/ading2210/poe-api/assets/30868335/0139c35c-aee8-4212-b6ef-667552f91936)

**Comment by xieqing520** [comment]
if (!window || !window['docu' + 'ment'] || !window[_0x4eeb76(0x1a9) + 'gato' + 'r'] || typeof process !== 'unde' + _0x4eeb76(0x199) + 'd' || typeof QuickJS !== 'unde' + _0x4eeb76(0x199) + 'd' || !window[_0x4eeb76(0x174) + 'nI8q' + 'sQ'])
                    return _0x477aff;

**Comment by xieqing520** [comment]
add this init code,while return ture form key:
`var window = {
	'document':{
		"aaaa":""
	},
	'navigator':"aaaaaaa",
	'xjCOnI8qsQ':true
};
var process = undefined
var QuickJS = undefined`

**Comment by wong2** [comment]
Wow the `QuickJS ` check makes me suspecting someone at Poe is watching this repo.

**Comment by ading2210** [comment]
I was looking at this a few hours ago, and I believe that they also changed the algorithm for generating `poe-tag-id`, although I haven't yet figured out exactly how it works.

**Comment by wong2** [comment]
I don't think `poe-tag-id` algorithm changed, because after bypass the `document`, `navigator`, ... checks, my project works fine now.

**Comment by GPT5free** [comment]
> Wow the `QuickJS ` check makes me suspect that someone at Poe is watching this repo.

yeah，you are right

**Comment by ading2210** [comment]
>add this init code,while return ture form key:
`var window = { 'document':{ "aaaa":"" }, 'navigator':"aaaaaaa", 'xjCOnI8qsQ':true }; var process = undefined var QuickJS = undefined`
@xieqing520 

This isn't enough to stop Poe from denying the requests. The `poe-tag-id` header needs to be reverse engineered again.

**Comment by canxin121** [comment]
> > add this init code,while return ture form key:
> > `var window = { 'document':{ "aaaa":"" }, 'navigator':"aaaaaaa", 'xjCOnI8qsQ':true }; var process = undefined var QuickJS = undefined`
> > @xieqing520
> 
> This isn't enough to stop Poe from denying the requests. The `poe-tag-id` header needs to be reverse engineered again.

i only changed the form key in my async poe client, and i just passed all the pytests.

**Comment by GPT5free** [comment]
> > > add this init code,while return ture form key:
> > > `var window = { 'document':{ "aaaa":"" }, 'navigator':"aaaaaaa", 'xjCOnI8qsQ':true }; var process = undefined var QuickJS = undefined`
> > > @xieqing520
> > 
> > 
> > This isn't enough to stop Poe from denying the requests. The `poe-tag-id` header needs to be reverse engineered again.
> 
> i only changed the form key in my async poe client, and i just passed all the pytests.

you solve it？

**Comment by ading2210** [comment]
This has been fixed in version 0.4.14.

**Comment by Qewertyy** [comment]
> This has been fixed in version 0.4.14.

umm.. the salt var isnt defined in extract_formkey method

**Comment by Qewertyy** [comment]
oh

**Comment by xieqing520** [comment]
i sure Poe is watching this repo.   i sleep 2hour, get new error

**Comment by dalaolala** [comment]
> > > add this init code,while return ture form key:
> > > `var window = { 'document':{ "aaaa":"" }, 'navigator':"aaaaaaa", 'xjCOnI8qsQ':true }; var process = undefined var QuickJS = undefined`
> > > @xieqing520
> > 
> > 
> > This isn't enough to stop Poe from denying the requests. The `poe-tag-id` header needs to be reverse engineered again.
> 
> i only changed the form key in my async poe client, and i just passed all the pytests.

Yes, if you write your own form key directly in poe.py,  can use it

**Comment by akl7777777** [comment]
must add "extensions": {
            "hash": "5fd489242adf25bf399a95c6b16de9665e521b76618a97621167ae5e11e4bce4"
        }
