### ISSUE TITLE
Consistent 400 Error after updating to poe-api 0.4.15

### ISSUE THREAD

**Issue by GPT5free** [ading2210/poe-api#191]
<img width="956" alt="image" src="https://github.com/ading2210/poe-api/assets/111382506/b64f8e2e-dba2-4041-8385-05de99eba905">

**Comment by CaoYunzhou** [comment]
```
INFO:root:Setting up session...
INFO:root:Downloading next_data...
INFO:root:Downloading channel data...
INFO:root:Downloading all bots...
INFO:root:Subscribing to mutations
INFO:websocket:Websocket connected
INFO:root:Sending message to capybara: Who are you?
I am Assistant, a virtual assistant powered by OpenAI's language model. I am designed to assist with a wide range of tasks, from answering questions and providing information to generating text and providing recommendations. How may I assist you today?INFO:root:Purging messages from capybara
INFO:root:Downloading 50 messages from capybara
INFO:root:Deleting messages: [2057873211, 2057873202, 2057873180]
```



```
INFO:root:Setting up session...
INFO:root:Downloading next_data...
INFO:root:Downloading channel data...
INFO:root:Downloading all bots...
INFO:root:Subscribing to mutations
WARNING:root:Server returned a status code of 400 while downloading https://poe.com/api/gql_POST. Retrying (1/10)...
WARNING:root:Server returned a status code of 400 while downloading https://poe.com/api/gql_POST. Retrying (2/10)...
WARNING:root:Server returned a status code of 400 while downloading https://poe.com/api/gql_POST. Retrying (3/10)...
WARNING:root:Server returned a status code of 400 while downloading https://poe.com/api/gql_POST. Retrying (4/10)...
WARNING:root:Server returned a status code of 400 while downloading https://poe.com/api/gql_POST. Retrying (5/10)...
WARNING:root:Server returned a status code of 400 while downloading https://poe.com/api/gql_POST. Retrying (6/10)...
WARNING:root:Server returned a status code of 400 while downloading https://poe.com/api/gql_POST. Retrying (7/10)...
WARNING:root:Server returned a status code of 400 while downloading https://poe.com/api/gql_POST. Retrying (8/10)...
WARNING:root:Server returned a status code of 400 while downloading https://poe.com/api/gql_POST. Retrying (9/10)...
WARNING:root:Server returned a status code of 400 while downloading https://poe.com/api/gql_POST. Retrying (10/10)...
Traceback (most recent call last):
  File "/home/caoyunzhou/poe-api/examples/temporary_message.py", line 9, in <module>
    client = poe.Client(token)
  File "/home/caoyunzhou/poe-api/poe-api/src/poe.py", line 154, in __init__
    self.connect_ws()
  File "/home/caoyunzhou/poe-api/poe-api/src/poe.py", line 420, in connect_ws
    self.setup_connection()
  File "/home/caoyunzhou/poe-api/poe-api/src/poe.py", line 196, in setup_connection
    self.subscribe()
  File "/home/caoyunzhou/poe-api/poe-api/src/poe.py", line 378, in subscribe
    result = self.send_query("SubscriptionsMutation", {
  File "/home/caoyunzhou/poe-api/poe-api/src/poe.py", line 365, in send_query
    r = request_with_retries(self.session.post, self.gql_url, data=payload, headers=headers)
  File "/home/caoyunzhou/poe-api/poe-api/src/poe.py", line 82, in request_with_retries
    raise RuntimeError(f"Failed to download {url} too many times.")
RuntimeError: Failed to download https://poe.com/api/gql_POST too many times.
```


I think there are internal personnel from Poe. I just updated the code and after 2 minutes, the code became unavailable. I gave up, oh my god

**Comment by akl7777777** [comment]
<img width="777" alt="image" src="https://github.com/ading2210/poe-api/assets/84266551/69a926a7-99e0-4144-bfc8-4d82e950bf67">

**Comment by isJN** [comment]
why are their developers so hardworking

**Comment by canxin121** [comment]
> why are their developers so hardworking

They are  watching at us.Poe-api updates,poe.com updates.

**Comment by CaoYunzhou** [comment]
> why are their developers so hardworking

They started paying attention to the updates of this repository in order to prevent us from using GPT, and paid high respect to the developers of Poe. Why should developers be difficult for developers @ading2210 ahh lol

**Comment by wong2** [comment]
Time to give up. :)

**Comment by isJN** [comment]
author is our hero

**Comment by Akut0** [comment]
they should stop this. If they are smart, they would just remove free gpt4 messages but hey... i think i need to find another provider for sending my money in. :)

@ading2210 
you are doing more than just a great job. :)

**Comment by GPT5free** [comment]
we can do something as  pandora， which a close source Project ，like this https://github.com/pengzhile/pandora
can provide a proxy url for prevent ban

**Comment by GenifeUA** [comment]
> we can do something as pandora， which a close source Project ，like this https://github.com/pengzhile/pandora can provide a proxy url for prevent ban @ading2210

Great idea!

**Comment by GPT5free** [comment]
besides，we can have a telegram group to discuss this to quicky solve bug

**Comment by asce0** [comment]
it still gives me this error:
RuntimeError: Failed to download https://poe.com/api/gql_POST too many times.

**Comment by Qewertyy** [comment]
> besides，we can have a telegram group to discuss this to quicky solve bug

could you share the group link?

**Comment by akl7777777** [comment]
I've almost did it , It seems that the new version formKey  has two additional characters compared to the previous one.
<img width="726" alt="image" src="https://github.com/ading2210/poe-api/assets/84266551/73122aa9-faee-4cdc-84ed-36ee21f67322">

**Comment by ZikaiSun** [comment]
> besides，we can have a telegram group to discuss this to quicky solve bug

Good idea, looking forward to be part of it...

**Comment by dalaolala** [comment]
> I've almost did it , It seems that the new version formKey has two additional characters compared to the previous one. <img alt="image" width="726" src="https://user-images.githubusercontent.com/84266551/255541894-73122aa9-faee-4cdc-84ed-36ee21f67322.png">

Use the website’s header formkey ， everything will be ok

**Comment by dalaolala** [comment]
This is the code i have update  about poe.py

https://code.ping8.top/edq4XNLr8e

and use for example

```
client = poe.Client(token,formkey)
```

**Comment by canxin121** [comment]
> This is the code i have update about poe.py
> 
> https://code.ping8.top/edq4XNLr8e
> 
> and use for example
> 
> ```
> client = poe.Client(token,formkey)
> ```

https://github.com/canxin121/Async-Poe-Client  In my async/aiohttp version ,I changed the formkey into content that users need to fill in ,too.

**Comment by ymyguang** [comment]
> This is the code i have update about poe.py
> 
> https://code.ping8.top/edq4XNLr8e
> 
> and use for example
> 
> ```
> client = poe.Client(token,formkey)
> ```

what is the value of formkey?

**Comment by SlasHTheGuardian** [comment]
> > This is the code i have update about poe.py
> > https://code.ping8.top/edq4XNLr8e
> > and use for example
> > ```
> > client = poe.Client(token,formkey)
> > ```
> 
> what is the value of formkey? it doesn't word when use "a7528be471ff054269fa7e5f069d082484"

Browser Devtools -> Network -> Receive POST -> Copy the value of the "poe-formkey"

**Comment by ymyguang** [comment]
> > > This is the code i have update about poe.py
> > > https://code.ping8.top/edq4XNLr8e
> > > and use for example
> > > ```
> > > client = poe.Client(token,formkey)
> > > ```
> > 
> > 
> > what is the value of formkey? it doesn't word when use "a7528be471ff054269fa7e5f069d082484"
> 
> Browser Devtools -> Network -> Receive POST -> Copy the value of the "poe-formkey"

have done,thanks for everyone！

**Comment by zhouhh2017** [comment]
Exception has occurred: TLSClientExeption
failed to do request: Get "https://poe.com": EOF

**Comment by ymyguang** [comment]
> Exception has occurred: TLSClientExeption failed to do request: Get "https://poe.com": EOF

do you use vpn?you should ignore tls if you use

**Comment by zhouhh2017** [comment]
Exception in thread INFO:root:Downloading 50 messages from a2
Thread-17:
Traceback (most recent call last):
  File "C:\anaconda\lib\threading.py", line 932, in _bootstrap_inner    self.run()
  File "C:\anaconda\lib\threading.py", line 870, in run    self._target(*self._args, **self._kwargs)
  File "C:\anaconda\lib\site-packages\poe.py", line 591, in recv_post_thread
    bot_message_id = self.active_messages[human_message_id]
KeyError: 2064042582
INFO:root:Deleting messages: [2064042593, 2064042582, 2064042551]

**Comment by asce0** [comment]
i tried everything and gives me this error:
    client = poe.Client(token,formkey=formkey)
TypeError: Client.__init__() got an unexpected keyword argument 'formkey'

**Comment by canxin121** [comment]
> i tried everything and gives me this error:
> client = poe.Client(token,formkey=formkey)
> TypeError: Client.**init**() got an unexpected keyword argument 'formkey'
https://github.com/canxin121/Async-Poe-Client try this

**Comment by ading2210** [comment]
This has been fixed in v0.4.13.

**Comment by claell** [comment]
Thanks so much! Let's see, how long it lasts ;)

**Comment by ading2210** [comment]
Probably not long, considering someone at Poe is definitely watching this repo.

**Comment by ading2210** [comment]
> we can do something as pandora， which a close source Project ，like this https://github.com/pengzhile/pandora
can provide a proxy url for prevent ban 
@GPT5free 

I don't intend to do this. Changing this to rely on a closed source proxy server goes against the spirit of this project.

**Comment by ading2210** [comment]
> Are you sure with "definitely"? I mean, could they also have seen suspicious requests to their servers (in possibly high volumes) and then analyzed the requests and blocked them based on certain unique criteria (talking about quickjs here as one example)? That blocking might even be done partly automated.
@claell 

The challenge script that QuickJS executes to generate the formkey does not send anything back to Poe's servers. That's the only time where QuickJS is used. So the only way Poe would know to check for it is if they looked at the source code for this library.

**Comment by gaowanliang** [comment]
Persisted for an hour 😭

**Comment by ading2210** [comment]
#193 to track this new issue.
