### ISSUE TITLE
Feature PR for golang version for poe-openapi-proxy

### ISSUE THREAD

**Issue by CaoYunzhou** [ading2210/poe-api#192]
- discribe: https://github.com/CaoYunzhou/poe-openai-proxy

I really like the Poe API project. I have created some Golang version code based on some basic functions, but now I am not familiar with CloudFlare. I hope someone can PR together and provide Poe proxy to more people. The code is a Golang code version that provides curl rest. Thank you for your willingness to provide code merge support

**Comment by ading2210** [comment]
Golang code will never be merged into this repo. This is intended to be a Python library only.
