### ISSUE TITLE
Status code of 403 on https//poe.com once again (0.4.16)

### ISSUE THREAD

**Issue by ading2210** [ading2210/poe-api#193]
```
(.venv) allen@dedipath-instance-1:~/projects/poe-api$ python3 examples/use_3rd_party_bot.py "xxxxxxxxxxxxxxxx%3D%3D"
INFO:root:Setting up session...
INFO:root:Downloading next_data...
WARNING:root:Server returned a status code of 403 while downloading https://poe.com. Retrying (1/10)...
WARNING:root:Server returned a status code of 403 while downloading https://poe.com. Retrying (2/10)...
WARNING:root:Server returned a status code of 403 while downloading https://poe.com. Retrying (3/10)...
WARNING:root:Server returned a status code of 403 while downloading https://poe.com. Retrying (4/10)...
WARNING:root:Server returned a status code of 403 while downloading https://poe.com. Retrying (5/10)...
WARNING:root:Server returned a status code of 403 while downloading https://poe.com. Retrying (6/10)...
WARNING:root:Server returned a status code of 403 while downloading https://poe.com. Retrying (7/10)...
WARNING:root:Server returned a status code of 403 while downloading https://poe.com. Retrying (8/10)...
WARNING:root:Server returned a status code of 403 while downloading https://poe.com. Retrying (9/10)...
WARNING:root:Server returned a status code of 403 while downloading https://poe.com. Retrying (10/10)...
Traceback (most recent call last):
  File "/home/allen/projects/poe-api/examples/use_3rd_party_bot.py", line 9, in <module>
    client = poe.Client(token)
             ^^^^^^^^^^^^^^^^^
  File "/home/allen/projects/poe-api/poe-api/src/poe.py", line 154, in __init__
    self.connect_ws()
  File "/home/allen/projects/poe-api/poe-api/src/poe.py", line 425, in connect_ws
    self.setup_connection()
  File "/home/allen/projects/poe-api/poe-api/src/poe.py", line 180, in setup_connection
    self.next_data = self.get_next_data(overwrite_vars=True)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/allen/projects/poe-api/poe-api/src/poe.py", line 235, in get_next_data
    r = request_with_retries(self.session.get, self.home_url)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/allen/projects/poe-api/poe-api/src/poe.py", line 82, in request_with_retries
    raise RuntimeError(f"Failed to download {url} too many times.")
RuntimeError: Failed to download https://poe.com too many times.
(.venv) allen@dedipath-instance-1:~/projects/poe-api$ 
```

**Comment by claell** [comment]
By the way (and I guess this is also true for the past issues), this is only a problem if one instantiates a new client. At least my running (very small!) instance (Python script with while loop) that is already instantiated still works for me and I can chat with it.

**Comment by ading2210** [comment]
I've also added an option to manually supply the formkey, which should allow the library to continue functioning in case the automatic formkey extraction gets patched again.

**Comment by Kot-nikot** [comment]
> Это было исправлено в v0.4.17.

Gotta do it again. They worked quickly. We wait v0.4.18.

**Comment by Ay-Da** [comment]
I tried it with all versions, but it doesn't work. :(

INFO:root:Setting up session...
INFO:root:Downloading next_data...
WARNING:root:Server returned a status code of 403 while downloading https://poe.com. Retrying (1/10)...
WARNING:root:Server returned a status code of 403 while downloading https://poe.com. Retrying (2/10)...
WARNING:root:Server returned a status code of 403 while downloading https://poe.com. Retrying (3/10)...
WARNING:root:Server returned a status code of 403 while downloading https://poe.com. Retrying (4/10)...
WARNING:root:Server returned a status code of 403 while downloading https://poe.com. Retrying (5/10)...
WARNING:root:Server returned a status code of 403 while downloading https://poe.com. Retrying (6/10)...
WARNING:root:Server returned a status code of 403 while downloading https://poe.com. Retrying (7/10)...
WARNING:root:Server returned a status code of 403 while downloading https://poe.com. Retrying (8/10)...
WARNING:root:Server returned a status code of 403 while downloading https://poe.com. Retrying (9/10)...
WARNING:root:Server returned a status code of 403 while downloading https://poe.com. Retrying (10/10)...
Traceback (most recent call last):
  File "C:\Users\user\Downloads\poe-api-main\poe-api-main\examples\temporary_message.py", line 9, in <module>
    client = poe.Client(token)
             ^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Roaming\Python\Python311\site-packages\poe.py", line 154, in __init__
    self.connect_ws()
  File "C:\Users\user\AppData\Roaming\Python\Python311\site-packages\poe.py", line 423, in connect_ws
    self.setup_connection()
  File "C:\Users\user\AppData\Roaming\Python\Python311\site-packages\poe.py", line 180, in setup_connection
    self.next_data = self.get_next_data(overwrite_vars=True)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Roaming\Python\Python311\site-packages\poe.py", line 233, in get_next_data
    r = request_with_retries(self.session.get, self.home_url)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Roaming\Python\Python311\site-packages\poe.py", line 82, in request_with_retries
    raise RuntimeError(f"Failed to download {url} too many times.")
RuntimeError: Failed to download https://poe.com too many times.
