### ISSUE TITLE
Websocket error

### ISSUE THREAD

**Issue by NabadyoCaano** [ading2210/poe-api#20]
Api was working perfectly before and i would get results for my queries on the shell or on a python script, it seems they have patched retrieval. I can still send questions, but i get the following error once i run it 
```
WARNING:root:Websocket returned error: 'data'
ERROR:websocket:error from callback <bound method Client.on_message of <poe.Client object at 0x000001BDADC18EE0>>: 'data'
WARNING:root:Websocket returned error: 'data'
ERROR:websocket:error from callback <bound method Client.on_message of <poe.Client object at 0x000001BDADC18EE0>>: 'data'
```
I have to go on the site to view the answers.

**Comment by ading2210** [comment]
Update to the latest version. This was fixed in 0.2.5.
