### ISSUE TITLE
Persistent Response Timed Out Issue Despite Successful Web Interface Conversations

### ISSUE THREAD

**Issue by fkx816** [ading2210/poe-api#200]
I encountered a "Response timed out" issue while using the latest library. 
The problem arises when I send a message using the library for the first time and it succeeds, but when I send the second message, I get a "Response timed out" notification. Upon checking on the web side, I found out that the message was successfully sent but there was no response. The problem persists even after reconnecting the client.
![Screenshot_20230725-191249](https://github.com/ading2210/poe-api/assets/69662155/860f2087-f737-443b-bfc7-674a0f2ba259)
There's no problem when conducting conversations through the web interface.

**Comment by fkx816** [comment]
![Uploading Screenshot_20230725-191542.png…]()

**Comment by fkx816** [comment]
![Screenshot_20230725-191542](https://github.com/ading2210/poe-api/assets/69662155/c8f1b876-940a-44db-b1f7-873479a96250)

**Comment by LanQian528** [comment]
I am also confused by this problem.

**Comment by LanQian528** [comment]
我发现这个问题造成的原因是这个上下文结构被针对了,使用这个结构就会导致响应超时,请立即更改上下文结构.

**Comment by fkx816** [comment]
> 我发现这个问题造成的原因是这个上下文结构被针对了,使用这个结构就会导致响应超时,请立即更改上下文结构.

完美解决问题

**Comment by isJN** [comment]
> > 我发现这个问题造成的原因是这个上下文结构被针对了,使用这个结构就会导致响应超时,请立即更改上下文结构.
> 
> 完美解决问题

Excuse me, how did you solve it? Did you modify or add any code to solve it?

**Comment by fkx816** [comment]
> > > 我发现这个问题造成的原因是这个上下文结构被针对了,使用这个结构就会导致响应超时,请立即更改上下文结构.
> > 
> > 
> > 完美解决问题
> 
> Excuse me, how did you solve it? Did you modify or add any code to solve it?
如果你的情况不是由上下文格式引起的，可能需要参见
#155
