### ISSUE TITLE
[Question] Does it still work?

### ISSUE THREAD

**Issue by LuluViBritannia** [ading2210/poe-api#204]
Hey there.
Is this project still working? I was using something very similar, a web interface called SillyTavern. I'd access Poe through it. Recently, that access stopped working completely.

I'd be interested in building a program with this project, but I need confidence that it still works. Thank you!

**Comment by isJN** [comment]
> 我不知道，但是...https://developer.poe.com/api-bots <---- 看，这是怎么回事？祝你好运！！！

Their official documentation is too messy, to be honest

**Comment by leeeawa** [comment]
![image](https://github.com/ading2210/poe-api/assets/114284437/e4d69403-4ef6-4401-aa00-98415dec42f5)
Yes,it works

**Comment by ading2210** [comment]
It should still work, although you might need to manually specify the formkey.
