### ISSUE TITLE
its time to see goodbye to poe

### ISSUE THREAD

**Issue by GPT5free** [ading2210/poe-api#207]
<img width="813" alt="image" src="https://github.com/ading2210/poe-api/assets/111382506/4f72dc56-c360-4e5c-b6ed-5903d71c5058">

**Comment by isJN** [comment]
yep

**Comment by CiaranYoung** [comment]
yeah..

**Comment by claell** [comment]
? I don't see any problem in the screenshot. What is this issue about?

**Comment by fkx816** [comment]
invalid issue
