### ISSUE TITLE
How can i llama bots?

### ISSUE THREAD

**Issue by xmi1an** [ading2210/poe-api#210]
How can i use llama bots

**Comment by phamxtien** [comment]
bots = {
            'Claude Instant'         : 'a2',
            'Claude Instant-100k'    : 'a2_100k',
            'Claude-2-100k'  : 'a2_2',
            'ChatGPT'        : 'chinchilla',
            'ChatGPT-16k'     : 'agouti',
            'ChatGPT-4'       : 'beaver',
            'Google PaLM2'    : 'acouchy',
            'Assistant'      : 'capybara',
            'LLAMA-2-70b'    : 'llama_2_70b_chat'
}

**Comment by xmi1an** [comment]
Working... Thank you so much for that..

**Comment by kbwzy** [comment]
any body knows which the dict of ChatGPT-4-32K?

**Comment by akl7777777** [comment]
> any body knows which the dict of ChatGPT-4-32K?

GPT-4-32k=vizcacha
