### ISSUE TITLE
send_chat_break

### ISSUE THREAD

**Issue by Katiboo** [ading2210/poe-api#213]
When calling client.send_chat_break(bot_name) returns an KeyError: 'AddMessageBreakMutation'

the code is trying to access the value associated with the key "AddMessageBreakMutation" in the "queries" dictionary, but that key does not exist in the dictionary.

**Comment by gaowanliang** [comment]
same problem, version 0.5.1

**Comment by ading2210** [comment]
This has been fixed in 0.5.2.
