### ISSUE TITLE
使用接口调用GPT4，回复的是GPT3.5的结果，而且没有扣除GPT4的次数

### ISSUE THREAD

**Issue by 31702160136** [ading2210/poe-api#217]
接口调用gpt4的结果，我们可以看到gpt4的次数并没有被扣除，而且回复的是gpt3.5的结果
<img width="858" alt="image" src="https://github.com/ading2210/poe-api/assets/46237986/411c086c-d69e-4c05-a852-e68d5ba120ce">

在poe网页使用gpt4的结果，我们可以看到gpt4的次数已经被扣除，回复的结果也是正确的
<img width="879" alt="image" src="https://github.com/ading2210/poe-api/assets/46237986/747844df-6767-4e47-bd66-440e67ff7197">

**Comment by akl7777777** [comment]
是的,逆向的就有这个问题,poe做了手脚,也不报错,就给你返回假数据

**Comment by ading2210** [comment]
Duplicate of #205.
