### ISSUE TITLE
Server returned a status code of 403 while downloading https://poe. com

### ISSUE THREAD

**Issue by Akut0** [ading2210/poe-api#218]
```
INFO:root:Setting up session...
INFO:root:Downloading next_data...
WARNING:root:Server returned a status code of 403 while downloading https://poe.
com. Retrying (1/10)...
WARNING:root:Server returned a status code of 403 while downloading https://poe.
com. Retrying (2/10)...
WARNING:root:Server returned a status code of 403 while downloading https://poe.
com. Retrying (3/10)...
WARNING:root:Server returned a status code of 403 while downloading https://poe.
com. Retrying (4/10)...
WARNING:root:Server returned a status code of 403 while downloading https://poe.
com. Retrying (5/10)...
WARNING:root:Server returned a status code of 403 while downloading https://poe.
com. Retrying (6/10)...
WARNING:root:Server returned a status code of 403 while downloading https://poe.
com. Retrying (7/10)...
WARNING:root:Server returned a status code of 403 while downloading https://poe.
com. Retrying (8/10)...
WARNING:root:Server returned a status code of 403 while downloading https://poe.
com. Retrying (9/10)...
WARNING:root:Server returned a status code of 403 while downloading https://poe.
com. Retrying (10/10)...
Traceback (most recent call last):
  File "start_bot.py", line 4, in <module>
    from plugin_chatgpt import GPT
  File "C:\MM Bot\plugin_chatgpt.py", line 74, in <module>
    poe_client = poe.Client(poe_token)
  File "C:\Python390\lib\site-packages\poe\__init__.py", line 156, in __init__
    self.connect_ws()
  File "C:\Python390\lib\site-packages\poe\__init__.py", line 446, in connect_ws

    self.setup_connection()
  File "C:\Python390\lib\site-packages\poe\__init__.py", line 182, in setup_conn
ection
    self.next_data = self.get_next_data(overwrite_vars=True)
  File "C:\Python390\lib\site-packages\poe\__init__.py", line 244, in get_next_d
ata
    r = request_with_retries(self.session.get, self.home_url)
  File "C:\Python390\lib\site-packages\poe\__init__.py", line 84, in request_wit
h_retries
    raise RuntimeError(f"Failed to download {url} too many times.")
RuntimeError: Failed to download https://poe.com too many times.
```

**Comment by raframil** [comment]
Happening with me too, on v0.5.2

**Comment by Toaster496** [comment]
same here

**Comment by cmldyu** [comment]
same problem

**Comment by 445022889** [comment]
一样的遭遇。

**Comment by media1demo** [comment]
yeah same here RuntimeError: Failed to download https://poe.com too many times.

**Comment by bolavefasfas** [comment]
Its hapenning on older versions as well i was in v0.4.x
Its sad i had lots of texts to summerize

**Comment by freQuensy23-coder** [comment]
Same problem(

**Comment by jeanantoine** [comment]
same here!

**Comment by Milou4Dev** [comment]
SAME

**Comment by chaney1030** [comment]
same

**Comment by Hafi-Ansari** [comment]
Unfortunately same :(

**Comment by double-zinc** [comment]
same here :(

**Comment by 31702160136** [comment]
我经过排查后发现使用GET访问https://poe.com提示403，Enable JavaScript and cookies to continue。我使用selenium库去访问https://poe.com可以成功获取到数据，但需要提前写入cookie：p-b、__cf_bm、cf_clearance才可以

**Comment by Hafi-Ansari** [comment]
"After investigating, I found that accessing https://poe.com/ using GET method prompts a 403 error, 'Enable JavaScript and cookies to continue.' I can successfully retrieve data by using the Selenium library to access https://poe.com/, but it requires writing the cookies: p-b, __cf_bm, and cf_clearance in advance."

is what @31702160136 is saying, but what exactly does this mean?

**Comment by 31702160136** [comment]
> "After investigating, I found that accessing https://poe.com/ using GET method prompts a 403 error, 'Enable JavaScript and cookies to continue.' I can successfully retrieve data by using the Selenium library to access https://poe.com/, but it requires writing the cookies: p-b, __cf_bm, and cf_clearance in advance."
> 
> is what @31702160136 is saying, but what exactly does this mean?

我对这方面不太熟悉，我认为是需要加载JavaScript后才可以获得到数据，我们通常使用代码进行GET请求页面是无法加载JavaScript的，但是使用浏览器就可以加载JavaScript

**Comment by Hafi-Ansari** [comment]
> > "After investigating, I found that accessing https://poe.com/ using GET method prompts a 403 error, 'Enable JavaScript and cookies to continue.' I can successfully retrieve data by using the Selenium library to access https://poe.com/, but it requires writing the cookies: p-b, __cf_bm, and cf_clearance in advance."
> > is what @31702160136 is saying, but what exactly does this mean?
> 
> 我对这方面不太熟悉，我认为是需要加载JavaScript后才可以获得到数据，我们通常使用代码进行GET请求页面是无法加载JavaScript的，但是使用浏览器就可以加载JavaScript

Have you confirmed that this method works?

**Comment by 445022889** [comment]
> 我经过排查后发现使用GET访问[https://poe.com提示403，Enable](https://poe.com%E6%8F%90%E7%A4%BA403%EF%BC%8CEnable) JavaScript and cookies to continue。我使用selenium库去访问[https://poe.com可以成功获取到数据，但需要提前写入cookie：p-b、__cf_bm、cf_clearance才可以](https://poe.com%E5%8F%AF%E4%BB%A5%E6%88%90%E5%8A%9F%E8%8E%B7%E5%8F%96%E5%88%B0%E6%95%B0%E6%8D%AE%EF%BC%8C%E4%BD%86%E9%9C%80%E8%A6%81%E6%8F%90%E5%89%8D%E5%86%99%E5%85%A5cookie%EF%BC%9Ap-b%E3%80%81__cf_bm%E3%80%81cf_clearance%E6%89%8D%E5%8F%AF%E4%BB%A5)

昨天用golang的chromedp访问好像也没问题，只需要加入p-b就行

**Comment by 31702160136** [comment]
> > 我经过排查后发现使用GET访问[https://poe.com提示403，启用](https://poe.com%E6%8F%90%E7%A4%BA403%EF%BC%8CEnable)JavaScript和cookie才能继续。我使用selenium去库访问[https://poe.com可以成功获取到数据，但需要提前写入cookie ：pb、__cf_bm、cf_clearance才可以](https://poe.com%E5%8F%AF%E4%BB%A5%E6%88%90%E5%8A%9F%E8%8E%B7%E5%8F%96%E5%88%B0%E6%95%B0%E6%8D%AE%EF%BC%8C%E4%BD%86%E9%9C%80%E8%A6%81%E6%8F%90%E5%89%8D%E5%86%99%E5%85%A5cookie%EF%BC%9Ap-b%E3%80%81__cf_bm%E3%80%81cf_clearance%E6%89%8D%E5%8F%AF%E4%BB%A5)
> 
> 昨天用golang的chromedp访问没什么问题，只需要加入pb就行

我试了一下，确实只需要pb，之前我需要加入__cf_bm和cf_clearance是因为浏览器有缓存

**Comment by 31702160136** [comment]
> > > “经过调查，我发现使用 GET 方法访问[https://poe.com/会提示 403 错误，'启用 JavaScript 和 cookies 即可继续'。](https://poe.com/)我可以使用 Selenium 库访问https://poe.com/成功检索数据，但需要提前写入cookie：pb、__cf_bm 和 cf_clearance。”
> > > 是什么@31702160136是这么说的，但这到底是什么意思呢？
> > 
> > 
> > 我对这方面还不太熟悉，我认为是需要加载JavaScript后才能获得数据，通常使用我们的代码进行GET请求页面是无法加载JavaScript的，但是使用浏览器就可以加载JavaScript
> 
> 你确认这个方法有效吗？

确实能有效获得到数据，但是又遇到了新的问题，提示’document‘ is not defined，可能是formkey算法变了

**Comment by tejas36026** [comment]
me too getting the same

**Comment by mahmuod711** [comment]
Same Problem

**Comment by YUFOHON** [comment]
same

**Comment by sycapple** [comment]
same

**Comment by RamyGomaa** [comment]
same on an older version too, looks like it's a general problem, not a version specific one.

**Comment by asce0** [comment]
does anyone get any idea about how to solve this error?

**Comment by kraravind** [comment]
getting the same issue, i went to poe, got the token value through inspect and ran the poe.Client and passed the token. This is the error below, please help:
File ~\anaconda3\Lib\site-packages\poe\__init__.py:156, in Client.__init__(self, token, proxy, headers, device_id, client_identifier, formkey)
    153 self.formkey_salt = None
    154 self.formkey = formkey
--> 156 self.connect_ws()

File ~\anaconda3\Lib\site-packages\poe\__init__.py:446, in Client.connect_ws(self, timeout)
    443 self.ws_connected = False
    445 if self.connect_count % 5 == 0:
--> 446   self.setup_connection()
    448 self.connect_count += 1
    450 ws = websocket.WebSocketApp(
    451   self.get_websocket_url(),
    452   header={"User-Agent": user_agent},
   (...)
    456   on_close=self.on_ws_close
    457 )

File ~\anaconda3\Lib\site-packages\poe\__init__.py:182, in Client.setup_connection(self)
    179 self.setup_count += 1
    181 self.ws_domain = f"tch{random.randint(1, 1e6)}"
--> 182 self.next_data = self.get_next_data(overwrite_vars=True)
    183 self.channel = self.get_channel_data()
    185 self.gql_headers = {
    186   "poe-formkey": self.formkey,
    187   "poe-tchannel": self.channel["channel"],
    188 }

File ~\anaconda3\Lib\site-packages\poe\__init__.py:244, in Client.get_next_data(self, overwrite_vars)
    241 def get_next_data(self, overwrite_vars=False):
    242   logger.info("Downloading next_data...")
--> 244   r = request_with_retries(self.session.get, self.home_url)
    245   json_regex = r'<script id="__NEXT_DATA__" type="application\/json">(.+?)</script>'
    246   json_text = re.search(json_regex, r.text).group(1)

File ~\anaconda3\Lib\site-packages\poe\__init__.py:84, in request_with_retries(method, *args, **kwargs)
     81       raise RuntimeError("Invalid or missing token.")
     82   logger.warn(f"Server returned a status code of {r.status_code} while downloading {url}. Retrying ({i+1}/{attempts})...")
---> 84 raise RuntimeError(f"Failed to download {url} too many times.")

RuntimeError: Failed to download https://poe.com/ too many times.

**Comment by siriani** [comment]
same error!

**Comment by mak448a** [comment]
Please stop bombing this thread unless if you actually have more information. It'll make it easier on the developers. Also, if you have the same issue, place a thumbs up on the first comment.

**Comment by teclectic** [comment]
Hi Guys,

Started getting this error on Saturday, I sent an email to Poe and they said that the specific IP has been blocked for 7 days. I have tried using my same token from another IP, I tried getting another account with a different token and all have come up with the same 403 error. I think that they must have some antiscraping software running which is flagging the API requests. Has anyone tried using sock5 proxies ? Any better ?

**Comment by bolavefasfas** [comment]
> Hi Guys,
> 
> Started getting this error on Saturday, I sent an email to Poe and they said that the specific IP has been blocked for 7 days. I have tried using my same token from another IP, I tried getting another account with a different token and all have come up with the same 403 error. I think that they must have some antiscraping software running which is flagging the API requests. Has anyone tried using sock5 proxies ? Any better ?

Did you try new account with new ip ?
And if they are banning or they have some mechanism in place and even if new ip with new account works it will be useless as it will be limited again right ?

**Comment by 4781121** [comment]
作者也不出来说两句, 也不知道是能解决还是不能解决

**Comment by akl7777777** [comment]
解决应该是能解决,但是一解决就会被盯上,估计也是难

**Comment by teclectic** [comment]
> > Hi Guys,
> > Started getting this error on Saturday, I sent an email to Poe and they said that the specific IP has been blocked for 7 days. I have tried using my same token from another IP, I tried getting another account with a different token and all have come up with the same 403 error. I think that they must have some antiscraping software running which is flagging the API requests. Has anyone tried using sock5 proxies ? Any better ?
> 
> Did you try new account with new ip ? And if they are banning or they have some mechanism in place and even if new ip with new account works it will be useless as it will be limited again right ?
> 
> I have tried with diffrent ip and diffrent account key still the error

Yes still get the same error. Any luck with proxies or selenium?

**Comment by jeanantoine** [comment]
> > > Hi Guys,
> > > Started getting this error on Saturday, I sent an email to Poe and they said that the specific IP has been blocked for 7 days. I have tried using my same token from another IP, I tried getting another account with a different token and all have come up with the same 403 error. I think that they must have some antiscraping software running which is flagging the API requests. Has anyone tried using sock5 proxies ? Any better ?
> > 
> > 
> > Did you try new account with new ip ? And if they are banning or they have some mechanism in place and even if new ip with new account works it will be useless as it will be limited again right ?
> > I have tried with diffrent ip and diffrent account key still the error
> 
> Yes still get the same error. Any luck with proxies or selenium?

I have you tried to set a Custom Device ID with new IP and account ?
from the README:

> Setting a Custom Device ID:
> 
> If you want to change the device ID that is being spoofed, you can use the poe.set_device_id, which accepts the following arguments:
> 
>     user_id - The user ID of the account you want to change the device ID for. The user ID can be found at client.viewer["poeUser"]["id"].
>     device_id - The new device ID. This is a 32 character UUID string in the following format: xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
> 
> poe.set_device_id("UGMlVXqlcLYyMOATMDsKNTMz", "6d659b04-043a-41f8-97c7-fb7d7fe9ad34")
> 
> The device IDs are saved to ~/.config/poe-api/device_id.json on Unix-like systems, and C:\Users\<user>\AppData\Roaming\poe-api\device_id.json on Windows.
> 
> Additionally, the poe.get_device_id function or client.device_id can be used to retrieve the saved device ID.
> 
> >>> poe.get_device_id("UGMlVXqlcLYyMOATMDsKNTMz")
> #6d659b04-043a-41f8-97c7-fb7d7fe9ad34
> 
> >>> client.device_id
> #6d659b04-043a-41f8-97c7-fb7d7fe9ad34"

**Comment by pythonhook** [comment]
How to resolve this,  guys

**Comment by wangyu1997** [comment]
感觉解决不了 放弃了一个月了 作者好像没有要解决的意思 换个库吧兄弟

**Comment by pythonhook** [comment]
有什么好的库推荐下呗



---Original---
From: "Wang ***@***.***&gt;
Date: Wed, Aug 9, 2023 15:20 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [ading2210/poe-api] Server returned a status code of 403 whiledownloading https://poe. com (Issue #218)




 
感觉解决不了 放弃了一个月了 作者好像没有要解决的意思 换个库吧兄弟

**Comment by 445022889** [comment]
> 有什么好的库推荐下呗
> […](#)
> ---Original--- From: "Wang ***@***.***&gt; Date: Wed, Aug 9, 2023 15:20 PM To: ***@***.***&gt;; Cc: ***@***.******@***.***&gt;; Subject: Re: [ading2210/poe-api] Server returned a status code of 403 whiledownloading https://poe. com (Issue #218) 感觉解决不了 放弃了一个月了 作者好像没有要解决的意思 换个库吧兄弟 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: ***@***.***&gt;
目前自己golang用的无头浏览器，劫持ws消息，勉强能用吧，不用一堆js，希望作者早日修复bug

**Comment by 445022889** [comment]
目前自己golang用的无头浏览器，劫持ws消息，勉强能用吧，不用一堆js，希望作者早日修复bug
> 有什么好的库推荐下呗
> […](#)
> ---Original--- From: "Wang ***@***.***&gt; Date: Wed, Aug 9, 2023 15:20 PM To: ***@***.***&gt;; Cc: ***@***.******@***.***&gt;; Subject: Re: [ading2210/poe-api] Server returned a status code of 403 whiledownloading https://poe. com (Issue #218) 感觉解决不了 放弃了一个月了 作者好像没有要解决的意思 换个库吧兄弟 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: ***@***.***&gt;

**Comment by teclectic** [comment]
Is it worth building the headless selenium solution in your opinion into
poe-api or otherwise? Did you also use proxies?

**Comment by ongspxm** [comment]
```
curl 'https://poe.com/' \
  -H 'authority: poe.com' \
  -H 'cookie: p-b=<token>' \
  -H 'user-agent: <copy user-agent>' --http2
```

after testing with curl
- found that both "authority" and "user-agent" header required
- http1.1 doesnt work (tested with `--http1.1` on curl and it gave the error)

but...
- requests is a 1.1 only library, maybe httpx might work?

**Comment by claell** [comment]
@ading2210 You added the help wanted label. Is there anything you need right now? Or are you just busy with other stuff right now?

**Comment by fanxyu** [comment]
希望作者能注意到这个问题，解决一下

**Comment by ading2210** [comment]
Sorry for the lack of an update, but I'm currently busy right now and won't be able to work on this for at least a week. Although if someone submits a PR that fixes this issue then I'll merge it and publish a new release.

**Comment by ading2210** [comment]
My current understanding of this bug is that Poe has started enforcing some sort of cloudflare-based verification which requires a full web browser.

**Comment by claell** [comment]
Alright, thanks for the update! If your understanding is correct, that would be rather sad to see.

@canxin121 I assume you experience the same problem with your async client?

**Comment by canxin121** [comment]
> 

not the same promblem, i can successfuly download the poe.com, but i can't send query successfullt.

**Comment by canxin121** [comment]
<img width="993" alt="image" src="https://github.com/ading2210/poe-api/assets/69547456/c6480ff0-144b-4043-98a9-bdb95e170c41">
async poe client didn't have this problem, but it could't extarct formkey, "document is not defined", it requires a browser environment to run the script? I could't find a way to do that expect for playwright. So i set formkey a must currently.But all other fuctions run well.

**Comment by mak448a** [comment]
> My current understanding of this bug is that Poe has started enforcing some sort of cloudflare-based verification which requires a full web browser.

Maybe selenium would work?

**Comment by 4781121** [comment]
@ading2210 可以参考这个项目, 他解决了目前的问题, https://github.com/canxin121/Async-Poe-Client

**Comment by ading2210** [comment]
> not the same promblem, i can successfuly download the poe.com, but i can't send query successfullt.
@canxin121 

Are you able to port those changes from your async client to this library?

**Comment by canxin121** [comment]
> > not the same promblem, i can successfuly download the poe.com, but i can't send query successfullt.
> > @canxin121
> 
> Are you able to port those changes from your async client to this library?

But my library don't have this downloading problem. I don't know why, perhaps because the headers? or aiohttp?I will try to find the reason.

**Comment by johnd0e** [comment]
https://github.com/x404xx/POE-Api seems ok

**Comment by GoAwayNow** [comment]
@ongspxm 
I got a 200 returned with a full set of browser cookies and the user-agent. I didn't use the authority header and made the request with http1.1. I don't know if it's the same for everyone, but it seems to be entirely a Cloudflare issue for me.

**Comment by tic-top** [comment]
寄！

**Comment by Iamprashanth-1** [comment]
try g4f pypi

**Comment by Nox998464** [comment]
https://github.com/snowby666/poe-api-wrapper is working for me

**Comment by ading2210** [comment]
I've fixed this in the latest commit, but the library is still broken due to changes in the `__NEXT_DATA__` format.
