### ISSUE TITLE
hard to get chatId

### ISSUE THREAD

**Issue by canxin121** [ading2210/poe-api#226]
Did you find the way to get chatid and chatcode of a bot?

**Comment by ading2210** [comment]
I'm trying to figure out their updated API as well, since most of my existing code was rendered obsolete by their recent changes.

See https://twitter.com/poe_platform/status/1691852115755643362

**Comment by canxin121** [comment]
I have found a little clue. Now I need to create a new conversation for a bot to get the chatId and chatcode of the conversation, and then continue the conversation with the same chatId and chatcode.

**Comment by snowby666** [comment]
I've just figured to get the chat ids of each bot. Hope this one help https://github.com/snowby666/poe-api-wrapper 
@canxin121

**Comment by canxin121** [comment]
> 

already finished the whole library, I'm updating the readme now, later i will publish a new version of async poe client
