### ISSUE TITLE
Can't find p-b cookie value

### ISSUE THREAD

**Issue by Jobians** [ading2210/poe-api#235]
![Screenshot_20230913-095805](https://github.com/ading2210/poe-api/assets/88005779/b44cfa95-cead-4bdc-be26-62047ad3ef6e)

**Comment by ading2210** [comment]
`p-b` is an HttpOnly cookie and thus cannot be accessed by Javascript.

https://developer.mozilla.org/en-US/docs/Web/HTTP/Cookies#restrict_access_to_cookies

**Comment by Jobians** [comment]
> `p-b` is an HttpOnly cookie and thus cannot be accessed by Javascript.
> 
> https://developer.mozilla.org/en-US/docs/Web/HTTP/Cookies#restrict_access_to_cookies

How to get it

**Comment by johnd0e** [comment]
DevTools in Kiwi Browser?

**Comment by Jobians** [comment]
> DevTools in Kiwi Browser?

I don't think so

**Comment by Jobians** [comment]
> DevTools in Kiwi Browser?

Bro thanks, I found it in Kiwi Browser

![Screenshot_20230917-113501](https://github.com/ading2210/poe-api/assets/88005779/7820c249-5c31-4198-a594-9b0a0aaea70c)
