### ISSUE TITLE
root:Server returned a status code of 504 while downloading https://poe.com/_next/data/0wjFveLlcYALex5VpEpwU/gpt-4.json. Retrying (1/10)...

### ISSUE THREAD

**Issue by 7trail** [ading2210/poe-api#24]
Hello,
I am getting this error when getting results. I'm not sure why, or what is causing it. Can you help?

**Comment by ading2210** [comment]
For whatever reason, the poe.com server occasionally gives a status of 504. This isn't an issue, since usually the request succeeds if we just resend it. If you don't want to see this message, just do `poe.logger.setLevel(logging.ERROR)`.

**Comment by ading2210** [comment]
Closing as this message is completely normal and I haven't received a response to this post in over a week.
