### ISSUE TITLE
Daily limit reached for capybara error

### ISSUE THREAD

**Issue by chirag127** [ading2210/poe-api#26]
![image](https://user-images.githubusercontent.com/76880977/230698599-7335f00b-9208-4e4c-b7ae-e4d7ab19dc48.png)

there is no limit on capybara but still getting the error

**Comment by zukixa** [comment]
Similar issue here, threading seems to cause the error, but calling the same message in a different space without threading, and there seems to be no limit?

Non-Threading, fully-functional example:
<img width="487" alt="Pasted Graphic 17" src="https://user-images.githubusercontent.com/56563509/230719956-69e1b30f-3c43-488b-beb1-8ebefbeea687.png">
Threading, broken example:
<img width="613" alt="Pasted Graphic 18" src="https://user-images.githubusercontent.com/56563509/230719981-02703793-49cd-4f45-a3ad-05feef4ae3c5.png">

**Comment by zukixa** [comment]
ID in poe.Client() is each the same

**Comment by zukixa** [comment]
Ended up being resolved on my end by changing the client cookie, don't know what it is ¯\_(ツ)_/¯ 

Might be some form of cookie expiration?
