### ISSUE TITLE
custom bots?

### ISSUE THREAD

**Issue by dm-vev** [ading2210/poe-api#27]
poe added new feature - custom bots.
how i can access to him with api?
![image](https://user-images.githubusercontent.com/80632449/230710993-b72f9379-ebd2-4bd0-ac02-890a446b4629.png)

**Comment by dm-vev** [comment]
and its crashes api, if custom bot created you cannot access any bot with api

**Comment by ading2210** [comment]
This has been fixed in the latest commit. It'll soon be incorporated into the next release.

**Comment by ading2210** [comment]
v0.2.9 has released, so run `pip3 install poe-api --upgrade` to get the fix.

**Comment by dm-vev** [comment]
thanks
