### ISSUE TITLE
ERROR:websocket:Connection to remote host was lost. - goodbye

### ISSUE THREAD

**Issue by jamezun** [ading2210/poe-api#33]
I am using version 2.9
I have this error after running for several hours, is it inevitable that the connection will close itself? 

USER: ERROR:websocket:Connection to remote host was lost. - goodbye
WARNING:root:Websocket closed with status None: None

**Comment by dayerqq** [comment]
After running for about an hour, I also encountered the same problem
ERROR:websocket:Connection to remote host was lost. - goodbye
WARNING:root:Websocket closed with status None: None

**Comment by Jxells** [comment]
I had the same problem

**Comment by ading2210** [comment]
I have zero clue why this is happening, but for now you should just recreate the Client object every hour or so.

**Comment by Barbery** [comment]
ERROR:websocket:'NoneType' object has no attribute 'sock' - goodbye

**Comment by ading2210** [comment]
This may have been fixed in 0.2.12.

**Comment by ading2210** [comment]
Closing as I believe the fix in 0.2.12 worked.
