### ISSUE TITLE
Using custom  bots

### ISSUE THREAD

**Issue by User1231300** [ading2210/poe-api#35]
Can it be implementeD?

**Comment by Yarkis01** [comment]
Hi @User1231300, this is already implemented in the latest version (0.2.9). Custom bots are used as classic bots. If you are talking about being able to create them via the API, no it is not possible yet.

**Comment by User1231300** [comment]
My bad. I found out that for some reason the bots are counted twice in the botlist, one time caps sensitive and the other. You always have to choose the bot in lowercase. Again my bad, sorry!
