### ISSUE TITLE
high interneet usage

### ISSUE THREAD

**Issue by lazezo2** [ading2210/poe-api#36]
after a few hours internet usage was around 500mb
is that normal?
how to save bandwidth

**Comment by maxcurrent420** [comment]
No I don't think that's not normal. Check your device for malware or background apps sucking it up maybe lol

**Comment by ading2210** [comment]
Yes, it is normal. Poe just sends its message responses in a really inefficient way. Instead of just sending the new text whenever the response is updated, it resends the entire response. There's nothing I can really do about this.
