### ISSUE TITLE
Extension of the formkey problem from the poe-api patch earlier today.

### ISSUE THREAD

**Issue by zukixa** [ading2210/poe-api#42]
Hi y'all -- after having followed the previous instructions on upgrading poe-api to fix the problem with the too-many-downloads, I started having a new problem.

<img width="644" alt="image" src="https://user-images.githubusercontent.com/56563509/232254687-6c63dea6-76eb-4e27-a5a2-56def72f8f19.png">

<img width="749" alt="image" src="https://user-images.githubusercontent.com/56563509/232254716-06fe1a5c-72c8-48f8-8f64-b65e61d1a4ea.png">

**Comment by xoiga123** [comment]
Maybe Poe employees are lurking in here :eyes:

**Comment by zukixa** [comment]
They should just make an actual free API for their service then 🥱

**Comment by App-le-Pie** [comment]
Is there a fix for this?

**Comment by ading2210** [comment]
> They scrambled the formkey to be generated with JS script and saved to window
@Cohee1207 

It seems as though that code is randomly generated on the server side, which makes it a bit trickier to decode with Python. A few regex queries should do the trick though.

**Comment by ading2210** [comment]
> Maybe Poe employees are lurking in here 👀
@xoiga123

It definitely feels like a quick patch just to try and deter unauthorized API usage.

**Comment by ading2210** [comment]
This has been fixed in 0.2.11.
