### ISSUE TITLE
A suggestion about function send_message

### ISSUE THREAD

**Issue by xyc0123456789** [ading2210/poe-api#48]
https://github.com/ading2210/poe-api/blob/eb4125aadf84c6edf5ed2e7424bc01328c7a60b8/poe-api/src/poe.py#L283-L284
In some cases, a message may not receive a reply due to network issues, which can cause the entire Q&A process to become stuck. To avoid this, it might be helpful to consider implementing a waiting timeout mechanism.

**Comment by ading2210** [comment]
This has been added in v0.4.3.
