### ISSUE TITLE
Poe gpt-4 loophole got Patched

### ISSUE THREAD

**Issue by vaibhavard** [ading2210/poe-api#49]
> Bad News! Editing or creating a bot with a free account using a paid bot type returns error

_WARNING:root:PoeBotCreateMutation returned an error: Server Error | Retrying (1/20)
WARNING:root:PoeBotCreateMutation returned an error: Server Error | Retrying (2/20)_

Related to #4

**Comment by Snowad14** [comment]
And they downgraded the versions (my bot was reset to GPT 3.5)

**Comment by aaravzer** [comment]
They did the same thing with Claude+ too

**Comment by ading2210** [comment]
Welp, it was fun for the 8 or so hours it lasted.
