### ISSUE TITLE
Does poe.com support embedding api?

### ISSUE THREAD

**Issue by keontang** [ading2210/poe-api#56]
such as:

'''python
openai.Embedding.create(
    input=[text],
    engine=CFG.get_azure_deployment_id_for_model(
           "text-embedding-ada-002"
    ),
)
'''

**Comment by ading2210** [comment]
This project does not try to imitate the original OpenAI API. The [xtekky/gpt4free](https://github.com/xtekky/gpt4free) library has a wrapper for this one that imitates the OpenAI API though.
