### ISSUE TITLE
Daily limit 

### ISSUE THREAD

**Issue by zc-eason** [ading2210/poe-api#57]
raise RuntimeError(f"Daily limit reached for {chatbot}.")
RuntimeError: Daily limit reached for beaver

**Comment by Yarkis01** [comment]
Everything is in the name of the error.
```py
raise RuntimeError(f"Daily limit reached for {chatbot}.")
RuntimeError: Daily limit reached for beaver
```
More seriously, Beaver corresponds to GPT-4, which has a limitation of one message per day, as specified in the README.
```
Note that, on free accounts, Claude+ (a2_2) has a limit of 3 messages per day and GPT-4 (beaver) has a limit of 1 message per day. For all the other chatbots, there seems to be a rate limit of 10 messages per minute.
```
