### ISSUE TITLE
ERROR:websocket:Connection to remote host was lost. - goodbye

### ISSUE THREAD

**Issue by eiweorerw** [ading2210/poe-api#64]
When the response is too long, WebSocket interruption may occur, causing the API to receive an incomplete response or only the latter part of it.

**Comment by ClassicOldSong** [comment]
I'm getting this error constantly, no matter I've requested or not, and once the error occur, the next query became extremely slow.
<img width="862" alt="image" src="https://github.com/ading2210/poe-api/assets/10512422/d6de60d4-d1ab-40e1-8f27-56f488a81aa6">
