### ISSUE TITLE
how to know when the token is expired?

### ISSUE THREAD

**Issue by dreammis** [ading2210/poe-api#65]
Thank you for the repository. I use it for my personal site as a bot.
Now I don't know when the token is expired. 
What exception will throw when the token is expired.

**Comment by ading2210** [comment]
An error is raised on [line 151](https://github.com/ading2210/poe-api/blob/eaf81df8cf8130ce6a8848465b600dc437e4f222/poe-api/src/poe.py#LL151C1-L152C68) if the token is invalid or expired: 
```python
    if not "availableBots" in self.viewer:
      raise RuntimeError("Invalid token or no bots are available.")
```

**Comment by dreammis** [comment]
I init the poe clicent at the service lanch.
so, You mean I need to call the function of get_bots every time before send message?

**Comment by ading2210** [comment]
No, get_bots is called on the class initialization.

**Comment by ading2210** [comment]
Sorry, I think I misunderstood your previous comment. No, you do not need to call get_bots every time you send a message. Simply using get_next_data should be sufficient (untested though):
```python
next_data = client.get_next_data()
viewer = next_data["props"]["pageProps"]["payload"]["viewer"]
if not "availableBots" in viewer:
  raise RuntimeError("Invalid token!")
```

**Comment by dreammis** [comment]
thank you, I will try then give you feedback 😊
