### ISSUE TITLE
If i use the Codename Beaver it uses GPT3 Instead of GPT-4

### ISSUE THREAD

**Issue by Lomusire** [ading2210/poe-api#68]
What is the curent codename Of GPT-4?

**Comment by qazplmqaz** [comment]
beaver

**Comment by Lomusire** [comment]
Thats weried i wanted to create an discord bot where i provide free GPT-4 accases to everyone (Added more than 200 premium poe tokens to it) but whenever somone uses the modell beaver it still uses gpt3 also whats the codename of the new cloude beta? Here is my github repo whith the sorce code: https://github.com/Lomusire/FreeGPT-4

**Comment by ading2210** [comment]
I can't seem to be able to reproduce this. For me, messages I send to `beaver` appear under the "GPT-4" chatbot when I use the Poe web client.

**Comment by Lomusire** [comment]
Sry forgot to close it yorkshire_lad helped me fix it long ago the codename beaver was actualy correct.
