### ISSUE TITLE
Completly Free Poe Premium tokens i sell nothing

### ISSUE THREAD

**Issue by Lomusire** [ading2210/poe-api#72]
This is not realy a issue but i provide hunderds of free Poe Premium 1 year tokens for free in my discord. make sure to credit me if you use the token in your project and also consider to run the gen yourself to keep the free GPT-4 project running

[https://discord.gg/qn3KuzKVzq](Discord)

**Comment by alqasemy2020** [comment]
Tried some of them and they actually worked.
I'm a bit curious like how did you get these tokens?

**Comment by TheLime1** [comment]
thank you can i use them in my [repo](https://github.com/TheLime1/gpt-cli) ? ill give you full credit in the README
