### ISSUE TITLE
Server Error

### ISSUE THREAD

**Issue by anfogy** [ading2210/poe-api#74]
Recently this pop up when Im using poe-api:
```
WARNING:root:SendMessageMutation returned an error: Server Error | Retry...
```

I tried to use poe.com instead and found out I can't login anymore, am I rate limited or got banned on poe?

This popup when I trying to login to poe.com, this popup:
```
Something went wrong. Please wait a moment and try again.
```

**Comment by TheLime1** [comment]
check #54
