### ISSUE TITLE
Request timeout

### ISSUE THREAD

**Issue by mamingsuper** [ading2210/poe-api#82]
I want use poe api to classify news and write a function to do it, but always fail due to time out problem.
Any tips and suggestions? Thanks in advance!

<img width="1187" alt="截屏2023-05-29 13 38 19" src="https://github.com/ading2210/poe-api/assets/55344946/b9d33673-287c-40c2-b7f2-e040a57266fb">

**Comment by ading2210** [comment]
Check the actual error message that you're getting. That RuntimeError might also occur if your account has somehow gotten banned.

**Comment by mamingsuper** [comment]
> Check the actual error message that you're getting. That RuntimeError might also occur if your account has somehow gotten banned.

thanks for the prompt reply. I find that during the implementation of these codes, it works for several cases, but has been banned by sage model, is there any methods to optimize?

**Comment by ading2210** [comment]
> I find that during the implementation of these codes, it works for several cases, but has been banned by sage model
@mamingsuper 

What do you mean by this? Are they filtering some of the messages that you send? If so, then there's really nothing I can do about it.

**Comment by mamingsuper** [comment]
> 
sorry for the confusion. I mean I have monitored the process and found that the codes run very well at the beginning, after several cases, my account was banned. Now, I cannot log in my Poe account.

**Comment by ading2210** [comment]
@mamingsuper What version of the library were you using when the account got banned?

**Comment by ading2210** [comment]
I'm going to close this issue since it's basically identical to #88.
