### ISSUE TITLE
Stuck at INFO:root:Downloading next_data

### ISSUE THREAD

**Issue by xoiga123** [ading2210/poe-api#83]
The changes to TLS spoofing got me stuck at `poe.Client(token)`. I had to downgrade to `poe-api==0.3.1`, and then it works with the same token. Is there a way to make TLS spoofing optional? I've tried changing `poe.headers` with https://headers.uniqueostrich18.repl.co/ and changing `client_identifier='chrome_xx'` but it's still stuck.

**Comment by Jxells** [comment]
![image](https://github.com/ading2210/poe-api/assets/94813798/3708cca0-5a2c-4bcd-8f1d-a4bc9f0f0388)
It's stuck here the whole time

**Comment by ading2210** [comment]
The ability to disable TLS spoofing has been added in v0.4.3. Simply pass in `None` as the `client_identifier` when creating the Client instance.
```python
client = poe.client("TOKEN_HERE", client_identifier=None)
```

**Comment by xoiga123** [comment]
For the record, apparently `tls_client` uses [a thread](https://github.com/FlorianREGAZ/Python-Tls-Client/blob/251ebd67c9aaac70e9a644b2bcca424bb3d9c4bf/tls_client/cookies.py#LL353C51-L353C51) and this causes a deadlock if used in conjunction with `multiprocessing.fork`. I had to [switch](https://pythonspeed.com/articles/python-multiprocessing/) to `multiprocessing.spawn`. TLS spoofing is working all good now. Ty :+1:
