### ISSUE TITLE
Poe banning accounts using this script (again)

### ISSUE THREAD

**Issue by hust-zXX** [ading2210/poe-api#88]
After I added an account and submitted multiple questions in a row, the following problems occurred when I logged in:
Something went wrong. Please wait a moment and try again.

But I have been waiting for 18 hours, and I still can't log in. Is it detected that my account has been banned?

**Comment by Jxells** [comment]
> 我添加账号后，连续提交了多个问题，登录时出现如下问题： Something went wrong. 请稍等片刻，然后重试。
> 
> 但是我已经等了18个小时了，还是登录不上去，是不是检测到我的账号被封禁了？

被ban了

**Comment by ading2210** [comment]
It's probably been banned. What version of the library were you using? Versions < 0.4.0 are known to be detectable by Poe.

**Comment by hust-zXX** [comment]
> It's probably been banned. What version of the library were you using? Versions < 0.4.0 are known to be detectable by Poe.

my version is 0.4.0

**Comment by kairui1108** [comment]
I have been banned right now, and my version is the latest, 0.4.2

**Comment by Anandkrishna34** [comment]
> > It's probably been banned. What version of the library were you using? Versions < 0.4.0 are known to be detectable by Poe.
> 
> my version is 0.4.0

Hey hust-zXX, I had the same issue. I contact poe support at you can get email at poe.com/contact or poe.com/support idk but if you tell poe that you can’t login with your account and send them the error message, they will unban you. You will get your old account fully back. But make sure to use temporary mail when using this api from now on

**Comment by Anandkrishna34** [comment]
> 

Do not tell you have been using this api

**Comment by TheLime1** [comment]
> use temporary mail when using this api from now on
@Anandkrishna34 
what temp emails you use , cuz they banned a lot of temp emails

**Comment by Anandkrishna34** [comment]
> > use temporary mail when using this api from now on
> 
> @Anandkrishna34 what temp emails you use , cuz they banned a lot of temp emails

Im using https://www.emailondeck.com/ and https://www.mohmal.com/en

**Comment by SuperLiveYou** [comment]
![image](https://github.com/ading2210/poe-api/assets/68497295/88040202-c06e-4c71-89db-31014c9c841c)
I used several accounts for testing and found that the ban seems to be due to Poe restricting each session, requiring a complete response before clearing the session and asking again. However, my previous account ban may have been caused by not restricting this and having many people using it simultaneously. I need to conduct long-term testing on this specific situation

**Comment by SuperLiveYou** [comment]
After a period of testing, I have basically determined the reason for the ban: it is because the session is requested or cleared again before the robot replies. But because I don't have enough accounts on hand, I can't determine whether requesting other robots before the request is completed will result in account lockdown. My current suggestion is to add a queue loop to the request to resolve account lockdown. However, I still want to know if requesting other robots before the request is completed will result in account lockdown, so does anyone have an extra account to help me test?

**Comment by Anandkrishna34** [comment]
> After a period of testing, I have basically determined the reason for the ban: it is because the session is requested or cleared again before the robot replies. But because I don't have enough accounts on hand, I can't determine whether requesting other robots before the request is completed will result in account lockdown. My current suggestion is to add a queue loop to the request to resolve account lockdown. However, I still want to know if requesting other robots before the request is completed will result in account lockdown, so does anyone have an extra account to help me test?

Use emailondeck

**Comment by ading2210** [comment]
> However, my previous account ban may have been caused by not restricting this and having many people using it simultaneously.
@ading2210

That seems likely, since normally it's not possible to send a message before the current response has completed. Implementing a global lock for sending messages on the entire account may be the only way to prevent this.

**Comment by showskyxmx** [comment]
> ![image](https://user-images.githubusercontent.com/68497295/243723281-24dd1ec8-b47f-4035-85b2-48220cb19e91.png) The queue loop can be so brief but effective in preventing account lockdowns, recommended to use

I have encountered the same problem. Could you please provide the detailed code for using "queue loop" in the project? I am not sure where to use it.

**Comment by Anandkrishna34** [comment]
I dont think it is becauseof clearing session before getting response

**Comment by fkx816** [comment]
> ![image](https://user-images.githubusercontent.com/68497295/243723281-24dd1ec8-b47f-4035-85b2-48220cb19e91.png) The queue loop can be so brief but effective in preventing account lockdowns, recommended to use

@SuperLiveYou 老哥用了这段代码后还有被ban过吗？
Have you been banned after using this code?

**Comment by SuperLiveYou** [comment]
> > ![image](https://user-images.githubusercontent.com/68497295/243723281-24dd1ec8-b47f-4035-85b2-48220cb19e91.png) The queue loop can be so brief but effective in preventing account lockdowns, recommended to use
> 
> @SuperLiveYou 老哥用了这段代码后还有被ban过吗？ Have you been banned after using this code?

稳如狗
Everything is absolutely normal.

**Comment by SuperLiveYou** [comment]
> I dont think it is becauseof clearing session before getting response

I think the more important reason is the multi threaded request for robot response, as well as the low version of the library. The UI interface restriction request was added a few weeks ago. The test results I conducted show that Poe does not ban you at the first time of your multi threaded request, but after multiple times. My test results may not be accurate, you can do some tests yourself @Anandkrishna34

**Comment by SuperLiveYou** [comment]
> > 经过一段时间的测试，我基本确定被ban的原因：是因为在机器人回复之前被再次请求或者清除。但是是因为我手头没有脚足够的账号，无法确定在请求完成之前请求其他机器人是否会引导账号被锁。我之前的建议是在请求中加入一个团队来解决决帐户锁定问题。不过我还是想知道在请求完成之之前请求请求其他机器人会不会导向账号被锁，请问有没有多少余的账号帮我测试下？
> 
> 在甲板上使用电子邮件

I think the more important reason is the multi threaded request for robot response, as well as the low version of the library. The UI interface restriction request was added a few weeks ago. The test results I conducted show that Poe does not ban you at the first time of your multi threaded request, but after multiple times. My test results may not be accurate, you can do some tests yourself

**Comment by SuperLiveYou** [comment]
> > After a period of testing, I have basically determined the reason for the ban: it is because the session is requested or cleared again before the robot replies. But because I don't have enough accounts on hand, I can't determine whether requesting other robots before the request is completed will result in account lockdown. My current suggestion is to add a queue loop to the request to resolve account lockdown. However, I still want to know if requesting other robots before the request is completed will result in account lockdown, so does anyone have an extra account to help me test?
> 
> Use emailondeck

Thank you for providing. I will take some time to test in the next few days

**Comment by SuperLiveYou** [comment]
> > ![image](https://user-images.githubusercontent.com/68497295/243723281-24dd1ec8-b47f-4035-85b2-48220cb19e91.png) The queue loop can be so brief but effective in preventing account lockdowns, recommended to use
> 
> I have encountered the same problem. Could you please provide the detailed code for using "queue loop" in the project? I am not sure where to use it.

Actually, all you need to do is ensure synchronous requests, without the need for queue loops. If you need it, I will provide

**Comment by fkx816** [comment]
> Actually, all you need to do is ensure synchronous requests, without the need for queue loops. If you need it, I will provide

希望老哥分享一下，感谢

**Comment by Anandkrishna34** [comment]
> > I dont think it is becauseof clearing session before getting response
> 
> I think the more important reason is the multi threaded request for robot response, as well as the low version of the library. The UI interface restriction request was added a few weeks ago. The test results I conducted show that Poe does not ban you at the first time of your multi threaded request, but after multiple times. My test results may not be accurate, you can do some tests yourself @Anandkrishna34

I said that because i never cleared session before reply

**Comment by Anandkrishna34** [comment]
> > > > I dont think it is becauseof clearing session before getting response
> > > 
> > > 
> > > I think the more important reason is the multi threaded request for robot response, as well as the low version of the library. The UI interface restriction request was added a few weeks ago. The test results I conducted show that Poe does not ban you at the first time of your multi threaded request, but after multiple times. My test results may not be accurate, you can do some tests yourself @Anandkrishna34
> > 
> > 
> > I said that because i never cleared session before reply
> 
> Have you ever sent a message before the current response has completed？

sometimes

**Comment by SuperLiveYou** [comment]
> > Actually, all you need to do is ensure synchronous requests, without the need for queue loops. If you need it, I will provide
> 
> 希望老哥分享一下，感谢

花了点时间写了个队列循环，可以看看
```python
import threading
import time
from collections import deque

class Queue():
    def __init__(self,func_handle) -> None:
        # 消息队列
        self.queue = deque()
        # 线程锁
        self.lock = threading.Lock()
        # 线程
        self.thread = threading.Thread(target=self.run)
        # 循环队列处理函数
        self.handle = func_handle
        self.thread.start()
    def append(self,item) -> None:
        with self.lock:
            self.queue.append(item)
    def run(self) -> None:
        while True:
            if len(self.queue) <= 0:
                # 如果队列为空，降低cpu占用
                time.sleep(0.3)
                continue
            # 获取队列中的下一个元素
            with self.lock:
                next = self.queue.popleft()
            if self.handle != None:
                self.handle(next)
```

使用此队列发送消息
```python
def handle(msg):
    for chunk in client.send_message("chinchilla", msg):
        pass
    # 处理你获得的消息chunk["text"]
    ......
queue = Queue(handle)
queue.append("测试")
```
注意，队列循环仅适用于使用多线程的情况下，比如QQ机器人框架，可能会有多个人同时请求时才需要用到队列循环，正常情况下不需要队列循环，你只需要保证没有开启异步或者多线程发送消息就行了

**Comment by fkx816** [comment]
> > > Actually, all you need to do is ensure synchronous requests, without the need for queue loops. If you need it, I will provide
> > 
> > 
> > 希望老哥分享一下，感谢
> 
> @fkx816 花了点时间写了个队列循环，可以看看
> 
> ```python
> import threading
> import time
> from collections import deque
> 
> class Queue():
>     def __init__(self,func_handle) -> None:
>         # 消息队列
>         self.queue = deque()
>         # 线程锁
>         self.lock = threading.Lock()
>         # 线程
>         self.thread = threading.Thread(target=self.run)
>         # 循环队列处理函数
>         self.handle = func_handle
>         self.thread.start()
>     def append(self,item) -> None:
>         with self.lock:
>             self.queue.append(item)
>     def run(self) -> None:
>         while True:
>             if len(self.queue) <= 0:
>                 # 如果队列为空，降低cpu占用
>                 time.sleep(0.3)
>                 continue
>             # 获取队列中的下一个元素
>             with self.lock:
>                 next = self.queue.popleft()
>             if self.handle != None:
>                 self.handle(next)
> ```
> 
> 使用此队列发送消息
> 
> ```python
> def handle(msg):
>     for chunk in client.send_message("chinchilla", msg):
>         pass
>     # 处理你获得的消息chunk["text"]
>     ......
> queue = Queue(handle)
> queue.append("测试")
> ```
> 
> 注意，队列循环仅适用于使用多线程的情况下，比如QQ机器人框架，可能会有多个人同时请求时才需要用到队列循环，正常情况下不需要队列循环，你只需要保证没有开启异步或者多线程发送消息就行了

感谢感谢

**Comment by Anandkrishna34** [comment]
> > > > I dont think it is becauseof clearing session before getting response
> > > 
> > > 
> > > I think the more important reason is the multi threaded request for robot response, as well as the low version of the library. The UI interface restriction request was added a few weeks ago. The test results I conducted show that Poe does not ban you at the first time of your multi threaded request, but after multiple times. My test results may not be accurate, you can do some tests yourself @Anandkrishna34
> > 
> > 
> > I said that because i never cleared session before reply
> 
> I understand what you said, but my testing involves doing both clearing sessions and requesting responses together, so I assume that both types of requests will cause this issue. I also believe that these two types of requests should be together at all times, not separately, so it doesn't matter. You just need to know that this may lead to account lockdowns If you need to clear the session separately, you may need to conduct some testing yourself to ensure that your account is not banned
> 
> Whether cleared or not, I do not believe that sending requests should continue until the reply is completed I have already made it very clear. If you don't understand, there's nothing I can do：（

yeah i understand

**Comment by Anandkrishna34** [comment]
> > > > I dont think it is becauseof clearing session before getting response
> > > 
> > > 
> > > I think the more important reason is the multi threaded request for robot response, as well as the low version of the library. The UI interface restriction request was added a few weeks ago. The test results I conducted show that Poe does not ban you at the first time of your multi threaded request, but after multiple times. My test results may not be accurate, you can do some tests yourself @Anandkrishna34
> > 
> > 
> > I said that because i never cleared session before reply
> 
> I understand what you said, but my testing involves doing both clearing sessions and requesting responses together, so I assume that both types of requests will cause this issue. I also believe that these two types of requests should be together at all times, not separately, so it doesn't matter. You just need to know that this may lead to account lockdowns If you need to clear the session separately, you may need to conduct some testing yourself to ensure that your account is not banned
> 
> Whether cleared or not, I do not believe that sending requests should continue until the reply is completed I have already made it very clear. If you don't understand, there's nothing I can do：（

But there is queue loop already. Check the poe.py 350 lines. Using temp mail while using this maybe the only way to prevent this

**Comment by ading2210** [comment]
I'm going to move the ban discussions to #118.
