### ISSUE TITLE
AttributeError: module 'websocket' has no attribute 'WebSocketApp'.

### ISSUE THREAD

**Issue by 40740** [ading2210/poe-api#92]
Traceback (most recent call last):
  File "G:\AI\poe\poe\poe-api-main\poe-api-main\examples\send_message.py", line 10, in <module>
    client = poe.Client('',client_identifier=None)
  File "C:\Users\lin85\AppData\Local\Programs\Python\Python310\lib\site-packages\poe.py", line 130, in __init__
    self.connect_ws()
  File "C:\Users\lin85\AppData\Local\Programs\Python\Python310\lib\site-packages\poe.py", line 336, in connect_ws
    self.ws = websocket.WebSocketApp(
AttributeError: module 'websocket' has no attribute 'WebSocketApp'. Did you mean: 'WebSocket'?

**Comment by SuperLiveYou** [comment]
This is a dependency conflict, and you may need a virtual environment and an "OS" package to solve this problem

**Comment by 40740** [comment]
Thank you, I'm trying

**Comment by SuperLiveYou** [comment]
I did the following when importing the package to ensure that it was in a virtual environment
import sys
sys.path.insert(0, 'poe\Lib\site-packages')
import poe

**Comment by SuperLiveYou** [comment]
![image](https://github.com/ading2210/poe-api/assets/68497295/34149050-1c6e-437f-a020-6c6ef6ddd5b2)
I created a virtual environment using virtualenv in the directory and installed the poe API in it. After exiting the virtual environment, I used the "sys" library in my code to introduce packages from the virtual environment. This is a very effective way to solve dependency conflicts. You can try it out

**Comment by SuperLiveYou** [comment]
> 这是一个依赖冲突，你可能需要一个虚拟环境和一个“OS”包来解决这个问题

I replied the wrong package here, it should be a 'sys' package

**Comment by ading2210** [comment]
This is an issue with your dependencies, not with this library. Check that the [websocket-client](https://pypi.org/project/websocket-client/) package is installed an on the latest version.
