### ISSUE TITLE
Sending multiple messages

### ISSUE THREAD

**Issue by Anandkrishna34** [ading2210/poe-api#95]
This is a suggestion that it would be cool if I could send multiple messages a time without finishing the response.it was like that older version. Could you give replacement code for the poe.py to do like it. It is in line 400 onwards. It is okay for me to get banned as I’m using temporary mail

**Comment by ading2210** [comment]
This isn't a priority for me, but I'll keep it in mind for a future version.

**Comment by Anandkrishna34** [comment]
Okay thanks
