### ISSUE TITLE
See bot id

### ISSUE THREAD

**Issue by Anandkrishna34** [ading2210/poe-api#96]
To edit a bot using this, I have to see botid but there is no way to see botid it will be good to print botid

**Comment by ading2210** [comment]
IIRC, when you create a bot, it gives you the bot ID, and the bot list in `client.bots` should also contain the bot's ID.

**Comment by Anandkrishna34** [comment]
> IIRC, when you create a bot, it gives you the bot ID, and the bot list in `client.bots` should also contain the bot's ID.

print(client.bots) ?

**Comment by SuperLiveYou** [comment]
The following code will output a dictionary with the robot ID and name. My approach is to invert the keys and values for ease of use, perhaps by inverting them on return
`python
print(json.dumps(client.bot_names,` indent=2))
"""
{
  "capybara": "Sage",
  "a2": "Claude-instant",
  "nutria": "Dragonfly",
  "a2_100k": "Claude-instant-100k",
  "beaver": "GPT-4",
  "chinchilla": "ChatGPT",
  "a2_2": "Claude+"
}
"""

**Comment by ading2210** [comment]
The bot ID is no longer needed for editing bots.
